### ISSUE TITLE
Cannot use [anywhere] rule to wrap production

### ISSUE THREAD

**Issue by Andrew-Miranti** [runtimeverification/k#1090]
I would like to use an anywhere rule to wrap all instances of a certain sort in my configuration in brackets.

With the definition
```
module TEST
  imports STRING
  
  syntax KItem ::= foo(X)

  syntax X ::= String
  syntax X ::= "<" X ">"

  rule T:X => < T > requires < _ > :/=K T [anywhere]

  configuration <k> foo($PGM:String) </k>
endmodule

module TEST-SYNTAX
  imports TEST
endmodule
```

The llvm backend is unwilling to compile this definition, crashing with the following error:
```
:~/Documents/test$ kompile --backend llvm test.k --debug
java.util.NoSuchElementException: key not found: rule0LHS
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.kframework.backend.llvm.matching.Parser$SymLib.$anonfun$signatures$1(Parser.scala:66)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Parser$SymLib.<init>(Parser.scala:62)
	at org.kframework.backend.llvm.matching.Parser$.parseSymbols(Parser.scala:251)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:18)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (key
not found: rule0LHS)
```

The haskell backend compiles the definition, but crashes with the following error at krun time:

```
kore-exec: Error in module 'TEST' -> alias 'rule0LHS' declaration (/home/andrewmiranti/Documents/test/./test-kompiled/definition.kore 372:9) -> \and (/home/andrewmiranti/Documents/test/./test-kompiled/definition.kore 374:10) -> (/home/andrewmiranti/Documents/test/./test-kompiled/definition.kore 374:10, /home/andrewmiranti/Documents/test/./test-kompiled/definition.kore 377:40): Expecting sort 'SortGeneratedTopCell{}' but got 'SortX{}'.
CallStack (from HasCallStack):
  error, called at app/share/GlobalMain.hs:452:36 in main:GlobalMain
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
```

The issue might be related to the sort requirement on the front end.  While it doesn't work on the latest master, on an older version of K (head detatched at 413f849a8) on the llvm backend the rule actually applied to the top cell of the configuration, yielding:

```
< <k>
  foo ( "abc" )
</k> >
```

**Comment by ehildenb** [comment]
As an `anywhere` rule, this will infinite loop. You probably can do this with a `macro` though.

Infinite loop: `< "blah" >`, then `"blah" => < "blah" >` and you have `< < "blah" > >`, then `"blah" => < "blah" >` and you have `< < < "blah" > > >`, etc...

An example of using `macro`s to wrap everything in a certain sort in a call to some function exists in KWasm here: https://github.com/kframework/wasm-semantics/blob/dae94b327066705a29fa1f5a7360cf0eee2a0264/data.md#type-information

Search for `macro`.

There it's used to allow us to parse correctly all `WasmIntToken` (which has different syntax than K `Int`), but then just immediately turn it into a K `Int`. It works because we identify everything that we want to be wrapped with a subsort, and `macro` will only expand once.

**Comment by ehildenb** [comment]
You need to use `macro-rec` to get it to expand repeatedly.

**Comment by Andrew-Miranti** [comment]
> As an `anywhere` rule, this will infinite loop. You probably can do this with a `macro` though.

I believe that is prevented by the side condition `< _ > :/=K T` - regardless, this isn't the behavior I'd expect even if it did infinite loop.  One backend refuses to compile the rule, and one crashes at runtime immediately.

**Comment by ehildenb** [comment]
In my example `T` was always `"blah"`, not `< "blah" >`.

**Comment by dwightguth** [comment]
This looks like a regression relating to Yi's work with aliases. I will investigate.

**Comment by dwightguth** [comment]
After looking at this definition in more detail, I notice a problem. The anywhere rule does not have a symbol at the top on the lhs, it has a variable, and I don't believe we support this case in the llvm backend. The following roughly equivalent definition seems to work correctly, once I apply a bug fix:

```
module TEST
  imports STRING

  syntax KItem ::= foo(X)

  syntax X ::= String [klabel(bar)]
  syntax X ::= "<" String ">"

  rule T:String => < T > [anywhere]

  configuration <k> foo($PGM:String) </k>
endmodule

module TEST-SYNTAX
  imports TEST
endmodule
```
