### ISSUE TITLE
Kompile failed on latest evm semantics

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#1121]
I tried to kompile evm semantics with the latest k and I got the following error:
```
$ kompile --debug --main-module ETHEREUM-SIMULATION --backend haskell --hook-namespaces KRYPTO --syntax-module ETHEREUM-SIMULATION .build/defn/haskell/driver.k --directory .build/defn/haskell -I .build/defn/haskell

org.kframework.utils.errorsystem.KEMException: [Error] Internal: Could not compute least upper bound for rewrite sort. Possible candidates: [JSON, JSONKey]
	Source(/home/zy/workspace/evm-semantics/./.build/defn/haskell/driver.k)
	Location(329,48,329,92)
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:126)
	at org.kframework.utils.errorsystem.KEMException.internalError(KEMException.java:68)
	at org.kframework.compile.AddSortInjections.lub(AddSortInjections.java:428)
	at org.kframework.compile.AddSortInjections.substituteProd(AddSortInjections.java:257)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.getSort(AddEmptyLists.java:145)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.lambda$getSort$4(AddEmptyLists.java:145)
	at org.kframework.compile.AddSortInjections.substituteProd(AddSortInjections.java:248)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.getSort(AddEmptyLists.java:145)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:94)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:273)
	at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:186)
	at org.kframework.kompile.DefinitionParsing.performParse(DefinitionParsing.java:423)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$17(DefinitionParsing.java:281)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	Suppressed: org.kframework.utils.errorsystem.KEMException: [Error] Internal: Could not compute least upper bound for rewrite sort. Possible candidates: [JSON, JSONKey]
	Source(/home/zy/workspace/evm-semantics/.build/defn/haskell/state-loader.k)
	Location(131,36,131,67)
		at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:126)
		at org.kframework.utils.errorsystem.KEMException.internalError(KEMException.java:68)
		at org.kframework.compile.AddSortInjections.lub(AddSortInjections.java:428)
		at org.kframework.compile.AddSortInjections.substituteProd(AddSortInjections.java:257)
		at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.getSort(AddEmptyLists.java:145)
		at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.lambda$getSort$4(AddEmptyLists.java:145)
		at org.kframework.compile.AddSortInjections.substituteProd(AddSortInjections.java:248)
		at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.getSort(AddEmptyLists.java:145)
		at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:94)
		at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
		at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
		at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
		at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
		at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
		at scala.collection.Iterator.foreach(Iterator.scala:929)
		at scala.collection.Iterator.foreach$(Iterator.scala:929)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
		at scala.collection.IterableLike.foreach(IterableLike.scala:71)
		at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
		at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
		at scala.collection.TraversableLike.map(TraversableLike.scala:234)
		at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
		at scala.collection.AbstractTraversable.map(Traversable.scala:104)
		at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
		at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
		at org.kframework.parser.concrete2kore.disambiguation.AddEmptyLists.apply(AddEmptyLists.java:137)
		... 107 more

```

The bug was introduced in the commit 9852fe2e4fae52663ac4eb1a0ef2726e495573b5

**Comment by dwightguth** [comment]
I am reasonably confident that #1119 will fix this when it is merged. I will test it to be sure tomorrow though and add more regression tests if it's not already fixed. In the meantime either build with that PR or with a slightly older version of k
