### ISSUE TITLE
Unhelpful error message from kprove: NullPointerException

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1175]
Made the following mistake when writing a small example module. In the spec, I use the expression `inc inc I`. `inc I` is a `Val`, but `inc` expects an `Int`. However, the error message gives no help catching this.

Module: `crash.k`

```
module CRASH
  imports DOMAINS

  configuration <k> $PGM:Val </k>

  syntax Val ::= "inc" Int | Int

  rule <k> inc I => I +Int 1 ... </k>

endmodule
```

Spec: `crash-spec.k`

```
module CRASH-SPEC

    rule <k> inc inc X => X +Int 2 ... </k>

endmodule
```

```
❯ kompile --backend haskell crash.k
[Warning] Compiler: Could not find main syntax module with name CRASH-SYNTAX in
definition.  Use --syntax-module to specify one. Using CRASH as default.
❯ kprove -m CRASH crash-spec.k --debug
java.lang.NullPointerException
        at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$8(DefinitionParsing.java:253)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:76)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:167)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:110)
        at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:253)
        at org.kframework.kompile.DefinitionParsing.parseModules(DefinitionParsing.java:129)
        at org.kframework.kompile.Kompile.parseModules(Kompile.java:371)
        at org.kframework.kprove.ProofDefinitionBuilder.build(ProofDefinitionBuilder.java:65)
        at org.kframework.kprove.KProve.run(KProve.java:57)
        at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:59)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)
```

**Comment by hjorthjort** [comment]
Actually, this doesn't work either and I'm stumped.

```
module CRASH
  imports DOMAINS

  configuration <k> $PGM:Val </k>

  syntax Val ::= "inc" Int

  rule <k> inc I:Int => I +Int 1 ... </k>

endmodule
```

```
module CRASH-SPEC

    rule <k> inc X => X +Int 1 ... </k>

endmodule
```

Error:

```
❯ kprove -m CRASH crash-spec.k --debug
java.lang.NullPointerException
        at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$8(DefinitionParsing.java:253)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:76)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:167)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:72)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:110)
        at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:253)
        at org.kframework.kompile.DefinitionParsing.parseModules(DefinitionParsing.java:129)
        at org.kframework.kompile.Kompile.parseModules(Kompile.java:371)
        at org.kframework.kprove.ProofDefinitionBuilder.build(ProofDefinitionBuilder.java:65)
        at org.kframework.kprove.KProve.run(KProve.java:57)
        at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:59)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)
```

**Comment by hjorthjort** [comment]
Just realized I'm not importing the `CRASH` module :man_facepalming:
Nevertheless, the error message isn't very helpful.
