### ISSUE TITLE
Error "key not found" for symbols from BYTES_IN_K when kompiling with --coverage

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1389]
It seems the `--coverage` flag causes an issue with symbols imported from `BYTES`. Maybe because `BYTES-IN-K` is only imported with `BYTES-SYMBOLIC`, but `BYTES-SYMBOLIC` is annotated `[kast]`, so it's included during parsing, but not during building coverage?

# How to reproduce

Module in `wasm.k`:

```
module WASM
    imports BYTES
endmodule
```

Kompile:

```
kompile --backend llvm --coverage  --debug wasm.k      \
    --directory .build/defn/llvm -I $(pwd)  \
    --main-module WASM
```

Output:

```
java.util.NoSuchElementException: key not found: _:__BYTES-IN-K_Bytes_Int_Bytes
        at scala.collection.MapLike.default(MapLike.scala:232)
        at scala.collection.MapLike.default$(MapLike.scala:231)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike.apply(MapLike.scala:141)
        at scala.collection.MapLike.apply$(MapLike.scala:140)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at org.kframework.compile.AddSortInjections.production(AddSortInjections.java:408)
        at org.kframework.compile.AddSortInjections.sort(AddSortInjections.java:319)
        at org.kframework.compile.GenerateCoverage.gen(GenerateCoverage.java:40)
        at org.kframework.backend.kore.KoreBackend.lambda$steps$7(KoreBackend.java:127)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromRuleBodyTransformerWithRule$1(transformers.scala:42)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$1(transformers.scala:16)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$3(transformers.scala:22)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.mutable.AbstractSet.map(Set.scala:46)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$2(transformers.scala:20)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:74)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:111)
        at org.kframework.backend.kore.KoreBackend.lambda$steps$8(KoreBackend.java:127)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at org.kframework.backend.kore.KoreBackend.lambda$steps$15(KoreBackend.java:160)
        at org.kframework.kompile.Kompile.run(Kompile.java:135)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(NoSuchElementException: key not found: _:__BYTES-IN-K_Bytes_Int_Bytes)
[Warning] Compiler: Could not find main syntax module with name WASM-SYNTAX in
definition.  Use --syntax-module to specify one. Using WASM as default.
```

This issue is blocking the Polkadot semantics:
* https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/polkadot-verification/detail/PR-115/7/pipeline
There, it's the `padLeftBytes` symbol from `BYTES-IN-K` that is missing.
When I try to `kompile` the Polkadot semantic locally, it's instead `_[_]_BYTES-IN-K_Int_Bytes_Int` that is missing.

**Comment by hjorthjort** [comment]
Here's the hierarchy of `BYTES` modules and their annotations. `A ---> B` means A imports B

![Bytes modules hierarchy](https://user-images.githubusercontent.com/8545447/86270441-873e8c80-bbcb-11ea-85d6-301e51b9d0ae.png)

**Comment by hjorthjort** [comment]
Could this be related to #1254, where the import structure of the `BYTES` modules changes, so that `BYTES-KORE` starts importing `BYTES-HOOKED` in a way that bypasses the `[concrete]` check?

**Comment by ehildenb** [comment]
FYI you can do `pyk graph-imports path/to/definition-kompiled` to get a graphviz PDF of the import structure...

**Comment by hjorthjort** [comment]
How do I make that call? Is there a CLI for  `pyk`?

**Comment by ehildenb** [comment]
Yeah, it's called `kpyk`. You'll need `PYTHONPATH` set. Something like `find kpyk` to find the executable, and `find pyk` to find what to set `PYTHONPATH` to.

You can do `kpyk --help`.
