### ISSUE TITLE
[Bug] kompile - Uncaught Exception, MatchError

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1439]
Running Kompile on the `conditional.bug` branch of the `c-semantics` repository causes a crash with a stack trace:

```
scala.MatchError: And(SortExps{},Application(Lblarg{},List(Application(Lbl'UndsQuesUndsColnUndsUnds'C-EXPRESSIONS-SYNTAX-RESTRICTED'Unds'Exp'Unds'Exp'Unds'Exp'Unds'Exp{},List(Application(inj{SortRVal{}, SortExp{}},List(Application(Lblrv'LParUndsCommUndsRParUnds'C-REPRESENTATION-SYNTAX'Unds'RVal'Unds'Value'Unds'Type{},List(Variable(VarV,SortValue{}), Variable(Var'Unds'0,SortType{}))))), Variable(Var'Unds'1,SortExp{}), Variable(VarE,SortExp{}))))),Application(Lblarg{},List(Variable(VarC,SortExp{})))) (of class org.kframework.parser.kore.implementation$ConcreteClasses$And)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:96)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$10(Generator.scala:99)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at org.kframework.backend.llvm.matching.Generator$.genPatterns(Generator.scala:99)
        at org.kframework.backend.llvm.matching.Generator$.$anonfun$genClauseMatrix$11(Generator.scala:134)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.kframework.backend.llvm.matching.Generator$.genClauseMatrix(Generator.scala:134)
        at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:22)
        at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
        at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:49)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:75)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type MatchError (MatchError:
And(SortExps{},Application(Lblarg{},List(Application(Lbl'UndsQuesUndsColnUndsUnds'C-EXPRESSIONS-SYNTAX-RESTRICTED'Unds'Exp'Unds'Exp'Unds'Exp'Unds'Exp{},List(Application(inj{SortRVal{},
SortExp{}},List(Application(Lblrv'LParUndsCommUndsRParUnds'C-REPRESENTATION-SYNTAX'Unds'RVal'Unds'Value'Unds'Type{},List(Variable(VarV,SortValue{}),
Variable(Var'Unds'0,SortType{}))))), Variable(Var'Unds'1,SortExp{}),
Variable(VarE,SortExp{}))))),Application(Lblarg{},List(Variable(VarC,SortExp{}))))
(of class org.kframework.parser.kore.implementation$ConcreteClasses$And))
```

**Comment by ehildenb** [comment]
Looks like we need to add a check to the frontend where an error is reported if the user puts a non-variable on the RHS of an `#as` pattern.
