### ISSUE TITLE
Bug kompile - Uncaught exeception thrown of type NoSuchElement

### ISSUE THREAD

**Issue by nblei** [runtimeverification/k#1563]
[Bug] kompile - crash when compiling

K Version
---------
```
RV-K version 1.0-SNAPSHOT
Git revision: 5e4e023
Git branch: UNKNOWN
Build date: Wed Sep 09 08:20:10 CDT 2020
```

Description
-----------

Running `kompile` causes an uncaught NoSuchElement exception to be thrown.
`--debug` provides the following stack trace

```
java.util.NoSuchElementException: key not found: isKResult
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.kframework.compile.AddSortInjections.production(AddSortInjections.java:410)
	at org.kframework.compile.AddSortInjections.sort(AddSortInjections.java:321)
	at org.kframework.compile.AddSortInjections.internalAddSortInjections(AddSortInjections.java:121)
	at org.kframework.compile.AddSortInjections.visitChildren(AddSortInjections.java:190)
	at org.kframework.compile.AddSortInjections.internalAddSortInjections(AddSortInjections.java:126)
	at org.kframework.compile.AddSortInjections.visitChildren(AddSortInjections.java:190)
	at org.kframework.compile.AddSortInjections.internalAddSortInjections(AddSortInjections.java:126)
	at org.kframework.compile.AddSortInjections.addInjections(AddSortInjections.java:71)
	at org.kframework.compile.AddSortInjections.addInjections(AddSortInjections.java:62)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$1(transformers.scala:16)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$3(transformers.scala:22)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$2(transformers.scala:20)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:74)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
	at org.kframework.backend.kore.KoreBackend.getKompiledModule(KoreBackend.java:102)
	at org.kframework.backend.kore.KoreBackend.getKompiledString(KoreBackend.java:89)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:45)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:75)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:119)
	at org.kframework.main.Main.runApplication(Main.java:109)
	at org.kframework.main.Main.main(Main.java:57)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
```

Input Files
-----------

File: `lambda.k`

```
// Copyright (c) 2012-2019 K Team. All Rights Reserved.

require "substitution.md"

module LAMBDA
  imports DOMAINS
  imports SUBSTITUTION

  // syntax Val ::= KVar
  //              | "lambda" KVar "." Exp  [binder, latex(\lambda{#1}.{#2})]
  syntax Exp ::= Val
               | Exp Exp              [strict, left]
               | "(" Exp ")"          [bracket]
  // syntax KResult ::= Val

  // rule (lambda X:KVar . E:Exp) V:Val => E[V / X]

  syntax Val ::= Int | Bool
  syntax Exp ::= Exp "*" Exp          [strict, left]
               | Exp "/" Exp          [strict]
               > Exp "+" Exp          [strict, left]
               > Exp "<=" Exp         [strict]
  rule I1 * I2 => I1 *Int I2
  rule I1 / I2 => I1 /Int I2
//  rule I1 / I2 => I1 /Int I2  requires I2 =/=Int 0
  rule I1 + I2 => I1 +Int I2
  rule I1 <= I2 => I1 <=Int I2
endmodule

```

Reproduction Steps
------------------

```
$ kompile lambda.k
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoSuchElementException: key not found: isKResult)
[Warning] Compiler: Could not find main syntax module with name LAMBDA-SYNTAX
in definition.  Use --syntax-module to specify one. Using LAMBDA as default.
```

Expected Behavior
-----------------

Succesful compilation or parser error.

**Comment by ehildenb** [comment]
This means we need to have an error in the frontend if the user uses `strict` attribute (or any other variants), but they don't have a sort named `KResult` declared or a `Bool` function named `isKResult` declared (and the same applies for non-`KResult` sorts used with `context`).

Also we should document in `pending-documentation.md` the "right" way to declare the function `isKResult` (ie. you need to define the function in sort `Bool` and it must be a `symbol`).
