### ISSUE TITLE
Kompile imp.k  NullPointerException on MacOS Catalin 10.15.6

### ISSUE THREAD

**Issue by davidstreader** [runtimeverification/k#1747]
[Bug] kompile - crash when compiling with kompile --debug imp.k
dstr@Dstr lesson_1 % kompile imp.k 
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NullPointerException: null)
dstr@Dstr lesson_1 % kompile --debug imp.k
java.lang.NullPointerException
	at org.kframework.parser.inner.disambiguation.TypeInferencer.<init>(TypeInferencer.java:97)
	at org.kframework.parser.inner.ParseInModule.parseStringTerm(ParseInModule.java:259)
	at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:185)
	at org.kframework.kompile.DefinitionParsing.performParse(DefinitionParsing.java:534)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$21(DefinitionParsing.java:309)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at scala.collection.convert.Wrappers$IteratorWrapper.forEachRemaining(Wrappers.scala:26)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:324)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$12(DefinitionParsing.java:281)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:79)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:74)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:75)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:74)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:75)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:74)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:113)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:281)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:252)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:196)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:182)
	at org.kframework.kompile.Kompile.run(Kompile.java:132)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)

[Bug] krun - segfault at runtime when dividing by zero

K Version
---------

Tell us what version of K you are using.
``
kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 
Git branch: UNKNOWN_BRANCH
Build date: Tue Jan 12 12:02:02 NZDT 2021
```

Description
-----------

ON  MacOS  loaded 
brew uninstall kframework; brew update; brew install kframework
As per https://stackoverflow.com/questions/65677623/k-framework-install-failure-on-macos-catalina-10-15-6

imp.k in /usr/local/Cellar/kframework/5.0.0/share/kframework/tutorial/1_k/2_imp/lesson_1

file is (I assume your standard)
// Copyright (c) 2014-2019 K Team. All Rights Reserved.

module IMP-SYNTAX
  imports DOMAINS-SYNTAX
  syntax AExp  ::= Int | Id
                 | "-" Int
                 | AExp "/" AExp              [left, strict]
                 > AExp "+" AExp              [left, strict]
                 | "(" AExp ")"               [bracket]
  syntax BExp  ::= Bool
                 | AExp "<=" AExp             [seqstrict, latex({#1}\leq{#2})]
                 | "!" BExp                   [strict]
                 > BExp "&&" BExp             [left, strict(1)]
                 | "(" BExp ")"               [bracket]
  syntax Block ::= "{" "}"
                 | "{" Stmt "}"
  syntax Stmt  ::= Block
                 | Id "=" AExp ";"            [strict(2)]
                 | "if" "(" BExp ")"
                   Block "else" Block         [strict(1)]
                 | "while" "(" BExp ")" Block
                 > Stmt Stmt                  [left]
  syntax Pgm ::= "int" Ids ";" Stmt
  syntax Ids ::= List{Id,","}
endmodule


module IMP
  imports IMP-SYNTAX
  imports DOMAINS
  syntax KResult ::= Int | Bool
endmodule

**Comment by dwightguth** [comment]
What does `z3 --version` show?

**Comment by davidstreader** [comment]
dstr@Dstr lesson_1 % z3 --version
dyld: Library not loaded: /gnatmail/sandbox/gpl-2016/x86_64-darwin/gcc/pkg/lib/libgomp.1.dylib
  Referenced from: /usr/local/bin/z3
  Reason: image not found
zsh: abort      z3 --version

I tried:
1. "brew uninstall z" but it  failed  "because it is required by kframework"
 2. "brew reinstall z3  but z3 --version  
and brew uninstall --ignore-dependencies z3;
gave same response

What seems to have worked is 

```
brew link --overwrite  z3         
Linking /usr/local/Cellar/z3/4.8.9_1... 30 symlinks created
dstr@Dstr lesson_1 % which z3                 
/usr/local/bin/z3
dstr@Dstr lesson_1 % z3 --version
Z3 version 4.8.9 - 64 bit
dstr@Dstr lesson_1 % kompile imp.k  
```
many thanks
