### ISSUE TITLE
[Bug] [kprove] - Failure with NullPointerException when building ProofDefinition

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1887]
K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 14483d1
Git branch: UNKNOWN
Build date: Fri Mar 26 21:50:06 UTC 2021
```

Description
-----------

Running `kprove` on a definition crashes when building the specification definition with an uninformative error message.

Input Files
-----------

The input `kmcd-gen.k`:

```
module FIXED-INT
  imports INT
  imports BOOL
  syntax FInt  ::=
    "(" FInt ")" [bracket]
  | "FInt" "(" value: Int "," one: Int ")" [klabel(FInt), symbol]
  syntax Int  ::=
    "baseFInt" "(" FInt ")" [function, klabel(baseFInt)]
  | "decimalFInt" "(" FInt ")" [function, klabel(decimalFInt)]
  rule baseFInt(FI) => value(FI) /Int one(FI)
  rule decimalFInt(FI) => value(FI) %Int one(FI)
  syntax FInt  ::=
    "0FInt" "(" Int ")"
  | "1FInt" "(" Int ")"
  rule 0FInt(ONE) => FInt(0  , ONE)  [macro]
  rule 1FInt(ONE) => FInt(ONE, ONE)  [macro]
  syntax FInt  ::=
    FInt "*FInt" FInt [function]
  | FInt "/FInt" FInt [function]
  | FInt "^FInt" Int [function]
  > FInt "+FInt" FInt [function]
  | FInt "-FInt" FInt [function]
  rule FInt(VALUE1, ONE1) *FInt FInt(VALUE2, ONE2) => FInt((VALUE1 *Int VALUE2) /Int ONE2             , ONE1)
  rule FInt(VALUE1, ONE1) /FInt FInt(VALUE2, ONE2) => FInt((VALUE1 *Int ONE2) /Int VALUE2             , ONE1) requires VALUE2 =/=Int 0
  rule FInt(VALUE1, ONE1) +FInt FInt(VALUE2, ONE2) => FInt(VALUE1 +Int ((VALUE2 *Int ONE1) /Int ONE2) , ONE1)
  rule FInt(VALUE1, ONE1) -FInt FInt(VALUE2, ONE2) => FInt(VALUE1 -Int ((VALUE2 *Int ONE1) /Int ONE2) , ONE1)
  rule FInt( VALUE, ONE) ^FInt E => FInt((VALUE ^Int E) /Int (ONE ^Int (E -Int 1)), ONE)          requires E  >Int 0
  rule FInt(_VALUE, ONE) ^FInt E => 1FInt(ONE)                                                    requires E ==Int 0
  rule FInt( VALUE, ONE) ^FInt E => FInt((ONE ^Int (1 -Int E)) /Int (VALUE ^Int (0 -Int E)), ONE) requires E  <Int 0
  syntax Bool  ::=
    FInt "<FInt" FInt [function]
  | FInt "<=FInt" FInt [function]
  | FInt ">FInt" FInt [function]
  | FInt ">=FInt" FInt [function]
  | FInt "==FInt" FInt [function]
  | FInt "=/=FInt" FInt [function]
  rule FInt(VALUE1, ONE1)   <FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2   <Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  <=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  <=Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)   >FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2   >Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  >=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  >=Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  ==FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  ==Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1) =/=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2 =/=Int VALUE2 *Int ONE1
endmodule

module KMCD-DATA
  imports BOOL
  imports FIXED-INT
  imports MAP
endmodule

module KMCD-DRIVER
  imports KMCD-DATA
  imports MAP
  imports STRING
  configuration <kmcd-driver>
          <k> $PGM:MCDSteps </k>
          <return-value> .K </return-value>
          <msg-sender> 0:Address </msg-sender>
          <this> 0:Address </this>
          <current-time> 0:Int </current-time>
          <call-stack> .List </call-stack>
          <pre-state> .K </pre-state>
          <events> .List </events>
          <tx-log> .Transaction </tx-log>
          <frame-events> .List </frame-events>
        </kmcd-driver>
  syntax MCDStep
  syntax MCDSteps  ::=
    ".MCDSteps"
  | MCDStep MCDSteps
  rule <k> .MCDSteps => . ... </k>
  rule <k> MCD:MCDStep MCDS:MCDSteps => MCD ~> MCDS ... </k>
  syntax MCDContract  ::=
    "contract" "(" MCDStep ")" [function, klabel(contract)]
  syntax Address  ::=
    Int
  | String
  | MCDContract
  syntax Event  ::=
    Transaction
  syntax Transaction  ::=
    ".Transaction" [klabel(.Transaction), symbol]
  | "Transaction" "(" acct: Address "," call: MCDStep "," events: List "," txException: Bool ")" [klabel(Transaction), symbol]
  syntax AdminStep  ::=
    "pushState"
  | "dropState"
  | "popState"
  | "assert"
endmodule

module KMCD
  imports KMCD-DRIVER
  configuration <kmcd>
        <kmcd-driver/>
      </kmcd>
endmodule

module KMCD-PROPS
  imports KMCD
  configuration <kmcd-properties>
          <kmcd/>
          <processed-events> .List </processed-events>
          <properties> .K </properties>
        </kmcd-properties>
endmodule

module KMCD-PRELUDE
  imports KMCD-PROPS
  syntax MCDStep  ::=
    "STEPS" "(" MCDSteps ")" [klabel(STEPS)]
  rule <k> STEPS ( MCDSTEPS ) => MCDSTEPS ... </k>
endmodule

module KMCD-GEN
  imports KMCD-PRELUDE
  imports BYTES
  configuration <kmcd-random>
        <kmcd-properties/>
        <kmcd-snapshots> .List </kmcd-snapshots>
        <kmcd-gen>
          <random> String2Bytes($RANDOMSEED:String) </random>
          <used-random> .Bytes </used-random>
          <generator-next> 0 </generator-next>
          <generator-current> 0 </generator-current>
          <generator-remainder> .K </generator-remainder>
          <generators>
            <generator multiplicity="*" type="Map">
              <generator-id> 0 </generator-id>
              <generator-steps> .K </generator-steps>
            </generator>
          </generators>
        </kmcd-gen>
      </kmcd-random>
endmodule
```

And input `spec-2.k`:

```
requires "kmcd-gen.k"

module VERIFICATION
    imports KMCD

    syntax KItem ::= runLemma ( Int ) | doneLemma ( Int )

    rule <k> runLemma(I) => doneLemma(I) ... </k>
endmodule

module SPEC-2
    imports VERIFICATION

    claim <k> runLemma(3 +Int 7) => doneLemma(10) ... </k>
endmodule
```

Reproduction Steps
------------------

```
$ kompile kmcd-gen.k --main-module KMCD-GEN --syntax-module KMCD-GEN --backend haskell
$ kprove spec-2.k -m VERIFICATION --debug
java.lang.NullPointerException
        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
        at org.kframework.Collections$.mutable(collections.scala:30)
        at org.kframework.Collections.mutable(collections.scala)
        at org.kframework.compile.SortCells.nthArgSort(SortCells.java:877)
        at org.kframework.compile.SortCells.access$900(SortCells.java:63)
        at org.kframework.compile.SortCells$3.apply(SortCells.java:582)
        at org.kframework.compile.SortCells$3.apply(SortCells.java:567)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.kore.TransformK.apply(TransformK.java:41)
        at org.kframework.kore.TransformK.apply(TransformK.java:15)
        at org.kframework.kore.KTransformer.apply(transformers.scala:12)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.compile.SortCells.resolveIncompleteCellFragment(SortCells.java:693)
        at org.kframework.compile.SortCells.sortCells(SortCells.java:96)
        at org.kframework.compile.SortCells.sortCells(SortCells.java:115)
        at org.kframework.compile.ConcretizeCells.concretize(ConcretizeCells.java:75)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$3(transformers.scala:22)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.mutable.AbstractSet.map(Set.scala:46)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$2(transformers.scala:20)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:77)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:74)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:114)
        at org.kframework.compile.ConcretizeCells.transformDefinition(ConcretizeCells.java:44)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at org.kframework.backend.kore.KoreBackend.lambda$steps$14(KoreBackend.java:177)
        at org.kframework.kprove.ProofDefinitionBuilder.compileDefinition(ProofDefinitionBuilder.java:101)
        at org.kframework.kprove.ProofDefinitionBuilder.build(ProofDefinitionBuilder.java:80)
        at org.kframework.kprove.KProve.run(KProve.java:67)
        at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:59)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)
```

Expected Behavior
-----------------

Either the proof should go through, or a more informative error message should be posted telling me what's wrong with the definition.

**Comment by ehildenb** [comment]
Let's timebox investigation on this one to half a day.

**Comment by radumereuta** [comment]
Here is a minimized version of the issue:
test.k:
```
module TEST-SYNTAX
endmodule

module TEST1
  imports INT
  configuration <c1> <k> .K </k> </c1>
endmodule

module TEST
  imports TEST1
  configuration <a> <c1/> <b> .K </b> </a>
endmodule
```
spec.k
```
requires "test.k"

module VERIFICATION
    imports TEST1

    syntax KItem ::= runLemma ( Int ) | doneLemma ( Int )

    rule <k> runLemma(I) => doneLemma(I) ... </k>
endmodule

module SPEC
    imports VERIFICATION

    claim <k> runLemma(3 +Int 7) => doneLemma(10) ... </k>
endmodule
```
```
$ kompile test.k --backend haskell
$ kprove spec.k -m VERIFICATION --debug
```
What happens is ConfigurationConcretization tries to apply on the spec rules, but at kompile time that step was based on the main module TEST, which declares more cells than TEST1 sees.

The quickest workaround is to kompile with `--main-module TEST1`
