### ISSUE TITLE
K fails to build C/C++ semantics

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#19]
When using K after commit 097e611ff2b3a2b22fcaa7b0c9334c86a43e3986 with newest rv-match backend, it fails to build the newest C/C++ semantics (91161bdb21b1cf86fb3398b2d0b299b84ceda442). Output:

```
Kompiling the static C++ semantics...
kompile -O2 --backend ocaml --non-strict --opaque-klabels c11/c11-translation.k --smt none cpp14/cpp14-translation.k -d "x86-gcc-limited-libc/cpp14-translation-kompiled" --no-prelude -w all -v --debug -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -I /path/to/c-semantics/x86-gcc-limited-libc/semantics
Parse command line options                                   =    37
Importing: Source(/path/to/c-semantics/semantics/./cpp14/cpp14-translation.k)
Importing: Source(/path/to/runtimeverification/k/k-distribution/target/release/k/include/builtin/kast.k)
Importing: Source(/path/to/runtimeverification/k/k-distribution/target/release/k/include/builtin/domains.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/translation.k)
... (a lot of stuff) ...
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/linking/resolution.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics/cpp-settings.k)
/tmp/tmp-kompile-8536276429347807810.l:2385: warning, rule cannot be matched
/tmp/tmp-kompile-4446192371551866502.l:18280: warning, rule cannot be matched
/tmp/tmp-kompile-5378504171804408025.l:49003: warning, rule cannot be matched
Parse definition [3182/3183 rules]                           = 113186
Apply compile pipeline                                       =  5356
java.lang.NoSuchMethodError: org.kframework.definition.Module.unresolvedLocalSentences()Lscala/collection/Set;
	at org.kframework.backend.ocaml.DefinitionToOcaml.lambda$initialize$9756c910$1(DefinitionToOcaml.java:245)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$279/860222046.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.initialize(DefinitionToOcaml.java:252)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:50)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
java.lang.NoSuchMethodError: org.kframework.definition.Module.unresolvedLocalSentences()Lscala/collection/Set;
	at org.kframework.backend.ocaml.DefinitionToOcaml.lambda$initialize$9756c910$1(DefinitionToOcaml.java:245)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$279/860222046.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.initialize(DefinitionToOcaml.java:252)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:50)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NoSuchMethodError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(org.kframework.definition.Module.unresolvedLocalSentences()Lscala/collection/Set;)
```
With the previous version of K (2ba519f691f355b31acb26fc22a7993fea188ce2), the output is a bit different:

```
...
Importing: Source(/home/jenda/Documents/School/DP/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
40 states, 1247 transitions, table size 5228 bytes
File "constants.ml", line 16601, characters 21-2993:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(ThreadLocal|Thread (_, _, _, _))
File "constants.ml", line 16638, characters 
...
Warning 58: no cmx file was found in path for module Gmp, and its interface was not compiled with -opaque
java.lang.NullPointerException
	at org.kframework.backend.ocaml.ConvertDataStructureToLookup.convert(ConvertDataStructureToLookup.java:581)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$351/550194951.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.convert(DefinitionToOcaml.java:279)
	at org.kframework.backend.ocaml.DefinitionToOcaml.ocamlMatchPattern(DefinitionToOcaml.java:379)
	at org.kframework.backend.ocaml.DefinitionToOcaml.interpreter(DefinitionToOcaml.java:550)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:134)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
java.lang.NullPointerException
	at org.kframework.backend.ocaml.ConvertDataStructureToLookup.convert(ConvertDataStructureToLookup.java:581)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$351/550194951.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.convert(DefinitionToOcaml.java:279)
	at org.kframework.backend.ocaml.DefinitionToOcaml.ocamlMatchPattern(DefinitionToOcaml.java:379)
	at org.kframework.backend.ocaml.DefinitionToOcaml.interpreter(DefinitionToOcaml.java:550)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:134)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (null)
[Warning] Compiler: missing entry for hook C_SEMANTICS.error
[Warning] Compiler: missing entry for hook C_SEMANTICS.nativeFunctions
```

K version 2ba519f691f355b31acb26fc22a7993fea188ce2 together with the semantics version d2f2c3584fbc980e8748738577e14f797a91c8e8 gives similar (the same?) error:

```
Step (Thread (_, _, _, [])::_, _)|
Step
  ((ThreadLocal|Bottom|KToken (_, _)|InjectedKLabel _|Map (_, _, _)|
   List (_, _, _)|Set (_, _, _)|Array (_, _)|Int _|Float (_, _, _)|String _|
   Bool _|KApply0 _|KApply1 (_, _)|KApply2 (_, _, _)|KApply3 (_, _, _, _)|
   KApply4 (_, _, _, _, _)|KApply5 (_, _, _, _, _, _)|
   KApply6 (_, _, _, _, _, _, _)|KApply7 (_, _, _, _, _, _, _, _)|
   KApply8 (_, _, _, _, _, _, _, _, _)|
   KApply9 (_, _, _, _, _, _, _, _, _, _)|
   KApply10 (_, _, _, _, _, _, _, _, _, _, _)|
   KApply12 (_, _, _, _, _, _, _, _, _, _, _, _, _)|
   KApply15 (_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))::_,
  _)|
Step ([], _))
File "run.ml", line 33, characters 9-1066:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
[]
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Gmp, and its interface was not compiled with -opaque
java.lang.NullPointerException
	at org.kframework.backend.ocaml.ConvertDataStructureToLookup.convert(ConvertDataStructureToLookup.java:581)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$352/1381237406.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.convert(DefinitionToOcaml.java:279)
	at org.kframework.backend.ocaml.DefinitionToOcaml.ocamlMatchPattern(DefinitionToOcaml.java:379)
	at org.kframework.backend.ocaml.DefinitionToOcaml.interpreter(DefinitionToOcaml.java:550)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:134)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
java.lang.NullPointerException
	at org.kframework.backend.ocaml.ConvertDataStructureToLookup.convert(ConvertDataStructureToLookup.java:581)
	at org.kframework.backend.ocaml.DefinitionToOcaml$$Lambda$352/1381237406.apply(Unknown Source)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.ocaml.DefinitionToOcaml.convert(DefinitionToOcaml.java:279)
	at org.kframework.backend.ocaml.DefinitionToOcaml.ocamlMatchPattern(DefinitionToOcaml.java:379)
	at org.kframework.backend.ocaml.DefinitionToOcaml.interpreter(DefinitionToOcaml.java:550)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:134)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (null)
[Warning] Compiler: missing entry for hook C_SEMANTICS.error
[Warning] Compiler: missing entry for hook C_SEMANTICS.nativeFunctions
```
K version 2ba519f691f355b31acb26fc22a7993fea188ce2 together with the semantics version 8c2641ba528f7082b5197896e4ce0e57193a8540 works fine. K version 097e611ff2b3a2b22fcaa7b0c9334c86a43e3986 with the same semantics fails on '--exit-code' being passed to 'kompile'. 

In all cases I had the latest ocaml backend (ocaml-backend-1.0-20170405.020916-316.jar), but I am not sure whether K used it every time - does it simply use the last accessible version?.

**Comment by dwightguth** [comment]
Can you check whether your K installation happens to have more than one ocaml-backend-1.0-* jar file in its lib/java directory? The error you report seems to be because of mismatch in version between K and the OCAML backend. The only thing I can think of is that you have multiple jars serving different versions of the same classes and the classloader is picking the wrong version.

**Comment by h0nzZik** [comment]
Yes, there were multiple versions of the backend. I removed them and run a clean build; it fixed the issue. Thank you.
