### ISSUE TITLE
Assertion failed in `FastRuleMatcher.java:361`

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#197]
```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: cb083f6
Git branch: master
Build date: Wed Nov 14 21:55:59 GMT 2018
```

Definition `crash.k`:
```
module CRASH-SYNTAX
     syntax KItem ::= foo() | stop()
endmodule
module CRASH
     imports CRASH-SYNTAX
     rule foo() => .List
endmodule
```
Kompile:
```
kompile --backend java --debug --main-module CRASH --syntax-module CRASH-SYNTAX crash.k --directory crash-kompiled
```

Specification `crash-spec.k`:
```
module CRASH-SPEC
     imports CRASH     
     // Crashes
     rule <k> foo() => ListItem(0) </k> [specification]     
     // works
     rule <k> (foo() => ListItem(0)) ~> stop() </k> [specification]
endmodule
```
Proof attempt:
```
kprove --debug --directory crash-kompiled crash-spec.k
```

Output (trimmed + debug):
```
Subject: .List()
Pattern: #KSequence(foo(.KList), R_DotVar0:K)
java.lang.AssertionError
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAssoc(FastRuleMatcher.java:361)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:307)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:255)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchRulePattern(FastRuleMatcher.java:91)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:160)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.proveRule(SymbolicRewriter.java:643)
```

**Comment by Isaac-DeFrain** [comment]
I'm also getting this same AssertionError...
```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: cc72c39
Git branch: UNKNOWN
Build date: Fri Feb 08 12:54:55 EST 2019
```
Full debug message:
```
$ krun tests/unpar1.btype --debug
java.lang.AssertionError
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAssoc(FastRuleMatcher.java:354)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:307)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:255)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchRulePattern(FastRuleMatcher.java:91)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:150)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:98)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:85)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:169)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
	at org.kframework.krun.KRun.run(KRun.java:88)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:107)
	at org.kframework.main.Main.main(Main.java:53)
java.lang.AssertionError
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAssoc(FastRuleMatcher.java:354)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:307)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:255)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchRulePattern(FastRuleMatcher.java:91)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:150)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:98)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:85)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:169)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
	at org.kframework.krun.KRun.run(KRun.java:88)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:107)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (null)
```

**Comment by ehildenb** [comment]
Closing because this is related to the Java backend, which has no more active development. Try on the Haskell backend and open a new issue if the problem persists.
