### ISSUE TITLE
On the centos6.9,build fail

### ISSUE THREAD

**Issue by dongbiao830415** [runtimeverification/k#20]
mvn package：
...........................
Tests run: 23, Failures: 0, Errors: 21, Skipped: 0, Time elapsed: 32.021 sec <<< FAILURE! - in org.kframework.parser.concrete2kore.RuleGrammarTest
test10(org.kframework.parser.concrete2kore.RuleGrammarTest)  Time elapsed: 1.531 sec  <<< ERROR!
org.kframework.utils.errorsystem.KEMException: [Error] Internal: gcc returned nonzero exit code. See output for details.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.internalError(KEMException.java:59)
	at org.kframework.parser.concrete2kore.kernel.Scanner.getScanner(Scanner.java:123)
	at org.kframework.parser.concrete2kore.kernel.Scanner.<init>(Scanner.java:38)
	at org.kframework.parser.concrete2kore.ParseInModule.getScanner(ParseInModule.java:115)
	at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInModule.java:104)
	at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:147)
	at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:121)
	at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:99)
	at org.kframework.parser.concrete2kore.RuleGrammarTest.parseRule(RuleGrammarTest.java:63)
	at org.kframework.parser.concrete2kore.RuleGrammarTest.test10(RuleGrammarTest.java:237)

gcc 7.1.0  Self compiled;
There will be no problem executing the “mvn package -DskipTests” command.

**Comment by dongbiao830415** [comment]
[root@localhost k-distribution]# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by dwightguth** [comment]
try installing flex and try again.

**Comment by dongbiao830415** [comment]
First install flex-devel, then "mvn package" is  OK !




dongbiao830415@foxmail.com
 
From: dwightguth
Date: 2017-07-12 00:09
To: runtimeverification/k
CC: dongbiao830415; Author
Subject: Re: [runtimeverification/k] On the centos6.9,build fail (#20)
try installing flex and try again.
