### ISSUE TITLE
[Bug] K does not work with java 16

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#2007]
Right now when you try to run `kompile` with java 16, you get the following stack trace:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @c81cdd1
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:503)
at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:359)
at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:799)
at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:469)
at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:456)
at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
at org.kframework.utils.BinaryLoader.loadSynchronized(BinaryLoader.java:152)
at org.kframework.utils.BinaryLoader.loadCache(BinaryLoader.java:106)
at org.kframework.kompile.DefinitionParsing.loadCaches(DefinitionParsing.java:167)
at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:260)
at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:204)
at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:213)
at org.kframework.kompile.Kompile.run(Kompile.java:138)
at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
at org.kframework.main.Main.runApplication(Main.java:118)
at org.kframework.main.Main.runApplication(Main.java:108)
at org.kframework.main.Main.main(Main.java:56)
```

It would appear that this is because the version of FST we are using for serialization is incompatible with newer access restrictions on reflection in Java. We will probably have to find a newer version of that library or else find a different library entirely. Regardless, this should be fixed as Java 17 is coming out later this year and is an LTS java release that a bunch of people are going to be switching to.

**Comment by ehildenb** [comment]
So far, it looks like our options are:

- Manually serialize things where FST doesn't support directly (lots of code).
- Switch to default library for serialization (est. 1-3s per invocation that has to read from caches, eg. kompile/kast/kprove).

One thing we can try to do _first_ (to simplify the choice above) is to be more careful about what we serialize:

- Trim down what we serialize/deserialize to minimize the affected footprint.
- Switch grammar serialization to use outer-k syntax and re-parse it instead of using a Java object serialization library. Need to time whether this is actually faster than then 1-3s hit we take using default Java serializer. kprove/kompile are not dominated by this serialization time, so not as big of a deal.
