### ISSUE TITLE
[Bug] [kompile] - failed to kompile seqstrict-predicate case

### ISSUE THREAD

**Issue by dongbiao830415** [runtimeverification/k#2067]
```
$ kompile --version
K version:    5.1.0
Git revision: a405729ee0db606f9a484de3612a901890dc68ed
Git branch:  master
Build date:   Fri Jul 09 21:35:21 CST 2021
```
I think the 0a12faff1e862800ab9b28e174ca8bcd39eec2ae commit introduced this bug

Description
-----------
cd k-distribution/tests/regression-new/seqstrict-predicate
$ kompile --syntax-module TEST --debug --no-exc-wrap --backend llvm  test.k -d . 

output error log:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void org.kframework.backend.kore.KoreBackend.<init>(org.kframework.kompile.KompileOptions, org.kframework.utils.file.FileUtil, org.kframework.utils.errorsystem.KExceptionManager, java.util.EnumSet, boolean)'
  at org.kframework.backend.haskell.HaskellBackend.<init>(Unknown Source)
  while locating org.kframework.backend.haskell.HaskellBackend
  while locating org.kframework.compile.Backend annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=9, type=MAPBINDER, keyType=java.lang.String)
  at org.kframework.kompile.BackendModule.configure(BackendModule.java:17) (via modules: org.kframework.kompile.KompileModule -> org.kframework.kompile.BackendModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.String, org.kframework.compile.Backend>
  at org.kframework.kompile.BackendModule.getKoreBackend(Unknown Source) (via modules: org.kframework.kompile.KompileModule -> org.kframework.kompile.BackendModule)
  while locating org.kframework.compile.Backend

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:68)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
Caused by: java.lang.NoSuchMethodError: 'void org.kframework.backend.kore.KoreBackend.<init>(org.kframework.kompile.KompileOptions, org.kframework.utils.file.FileUtil, org.kframework.utils.errorsystem.KExceptionManager, java.util.EnumSet, boolean)'
	at org.kframework.backend.haskell.HaskellBackend.<init>(HaskellBackend.java:26)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:547)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:529)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:143)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	... 5 more
[Error] Internal: Uncaught exception thrown of type ProvisionException (ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void org.kframework.backend.kore.KoreBackend.<init>(org.kframework.kompile.KompileOptions, org.kframework.utils.file.FileUtil, org.kframework.utils.errorsystem.KExceptionManager, java.util.EnumSet, boolean)'
  at org.kframework.backend.haskell.HaskellBackend.<init>(Unknown Source)
  while locating org.kframework.backend.haskell.HaskellBackend
  while locating org.kframework.compile.Backend annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=9, type=MAPBINDER, keyType=java.lang.String)
  at org.kframework.kompile.BackendModule.configure(BackendModule.java:17) (via modules: org.kframework.kompile.KompileModule -> org.kframework.kompile.BackendModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.String, org.kframework.compile.Backend>
  at org.kframework.kompile.BackendModule.getKoreBackend(Unknown Source) (via modules: org.kframework.kompile.KompileModule -> org.kframework.kompile.BackendModule)
  while locating org.kframework.compile.Backend

1 error)

**Comment by ehildenb** [comment]
This usually only happens if you:

- don't have a clean build (do a `mvn clean` then retry), or
- are using a different version of the tool between runs (eg. `kompile` with version 5.1.34 but `krun` with version 5.1.50).

Can you try a clean build and then report back?

**Comment by dongbiao830415** [comment]
Steps:
```
cd k
rm -rf *
git checkout -- .
rm -rf k-distribution/bin
mvn  package -Dmaven.test.skip=true
dir=`pwd`
ln -s $dir/k-distribution/target/release/k/bin $dir/k-distribution
cd k-distribution/tests/regression-new/seqstrict-predicate
$dir/k-distribution/bin/kompile --syntax-module TEST --no-exc-wrap --debug --backend llvm  test.k -d .
```
Still the same error

**Comment by dongbiao830415** [comment]
Steps:

cd k
rm -rf *
git checkout -- .
rm -rf k-distribution/bin
mvn  package -Dmaven.test.skip=true
dir=`pwd`
ln -s $dir/k-distribution/target/release/k/bin $dir/k-distribution
cd k-distribution/tests/regression-new/seqstrict-predicate
$dir/k-distribution/bin/kompile --syntax-module TEST --no-exc-wrap --debug --backend llvm  test.k -d .
Still the same error

**Comment by ehildenb** [comment]
You're linking line `ln -s ...` will not work. You need to instead put `k-distribution/target/release/k/bin` on `PATH`, not symlink to it.

You definitely should not be making that symlink, as it will conflict with the existing k-distribution.

**Comment by ehildenb** [comment]
What you likely need to be doing:

```
cd k
rm -rf *
git checkout -- .
rm -rf k-distribution/bin
mvn  package -Dmaven.test.skip=true
export PATH=$(pwd)/k-distribution/target/release/k/bin:$PATH
cd k-distribution/tests/regression-new/seqstrict-predicate
kompile --syntax-module TEST --no-exc-wrap --debug --backend llvm  test.k -d .
```

**Comment by radumereuta** [comment]
Please reopen if it's still an issue.
