### ISSUE TITLE
Error while compiling lambda.k

### ISSUE THREAD

**Issue by dongbiao830415** [runtimeverification/k#22]
When using kompile, it fails to compile the lambda.k(a very simple example). 

cat lambda.k 
```
[root@localhost hello]# cat lambda.k 
// Copyright (c) 2012-2016 K Team. All Rights Reserved.
module LAMBDA-SYNTAX
  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
endmodule
```
(1)  kompile --no-prelude lambda.k. Output:
```
[root@localhost hello]# kompile --no-prelude lambda.k 
[Error] Compiler: Could not find sorts: [Id]
	Source(/root/src/c-semantics/hello/./lambda.k)
	Location(4,18,4,19)
```
(2)  kompile lambda.k. Output:
```
[root@localhost hello]# kompile lambda.k
[Error] Compiler: Could not find main module with name LAMBDA in definition.
Use --main-module to specify one.
```
I don't know what the reason is.
Who has the latest K manual?
Thank you.

**Comment by dongbiao830415** [comment]
[root@localhost hello]# cat lambda.k 
'''
// Copyright (c) 2012-2016 K Team. All Rights Reserved.
module LAMBDA-SYNTAX
  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
endmodule

module LAMBDA
    imports LAMBDA-SYNTAX
endmodule
'''
[root@localhost hello]# kompile --no-prelude lambda.k 
[Error] Compiler: Could not find sorts: [Id]
	Source(/root/src/c-semantics/hello/./lambda.k)
	Location(4,18,4,19)

[root@localhost hello]# kompile  lambda.k 
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (None.get)

**Comment by dongbiao830415** [comment]
I compiled the K framework using the runtimeverification/k repository. My kcc works just fine(I feel like kcc is just a demo).
Many of the K  files in the runtimeverification/k project do not compile properly。

(1)  kompile --no-prelude --debug lambda.k 
```
[root@localhost hello]# kompile --no-prelude --debug lambda.k 
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Could not find sorts: [Id]
	Source(/root/src/c-semantics/hello/./lambda.k)
	Location(4,18,4,19)
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:87)
	at org.kframework.definition.Module$$anonfun$checkSorts$1.apply(outer.scala:235)
	at org.kframework.definition.Module$$anonfun$checkSorts$1.apply(outer.scala:231)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.kframework.definition.Module.checkSorts(outer.scala:231)
	at org.kframework.kore.convertors.KILtoKORE.apply(KILtoKORE.java:130)
	at org.kframework.kore.convertors.KILtoKORE.apply(KILtoKORE.java:80)
	at org.kframework.parser.concrete2kore.ParserUtils.lambda$loadModules$41(ParserUtils.java:205)
	at org.kframework.parser.concrete2kore.ParserUtils$$Lambda$32/837108062.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.kframework.parser.concrete2kore.ParserUtils.loadModules(ParserUtils.java:205)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:237)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:220)
	at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:169)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:149)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Could not find sorts: [Id]
	Source(/root/src/c-semantics/hello/./lambda.k)
	Location(4,18,4,19)
```
(2)  kompile  --debug ./lambda.k 
```
[root@localhost hello]# kompile  --debug ./lambda.k 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$51(DefinitionParsing.java:192)
	at org.kframework.kompile.DefinitionParsing$$Lambda$68/1446922577.apply(Unknown Source)
	at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103)
	at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:76)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:196)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:155)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$51(DefinitionParsing.java:192)
	at org.kframework.kompile.DefinitionParsing$$Lambda$68/1446922577.apply(Unknown Source)
	at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103)
	at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:76)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:196)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:155)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (None.get)

**Comment by grosu** [comment]
Remove the `--no-prelude` option and it should work.

Grigore


________________________________

**Comment by grosu** [comment]
If you just want to use kcc, we recommend that you download RV-Match (https://runtimeverification.com/match/)

Grigore


________________________________

**Comment by dongbiao830415** [comment]
[root@localhost hello]# kompile --debug ./lambda.k java.util.NoSuchElementException: None.get at scala.None$.get(Option.scala:347) at scala.None$.get(Option.scala:345) at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$51(DefinitionParsing.java:192) at org.kframework.kompile.DefinitionParsing$$Lambda$68/1446922577.apply(Unknown Source) at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103) at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103) at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:76) at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71) at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901) at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71) at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67) at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115) at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:196) at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:155) at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135) at org.kframework.kompile.Kompile.run(Kompile.java:121) at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69) at org.kframework.main.FrontEnd.main(FrontEnd.java:52) at org.kframework.main.Main.runApplication(Main.java:113) at org.kframework.main.Main.runApplication(Main.java:103) at org.kframework.main.Main.main(Main.java:52) java.util.NoSuchElementException: None.get at scala.None$.get(Option.scala:347) at scala.None$.get(Option.scala:345) at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$51(DefinitionParsing.java:192) at org.kframework.kompile.DefinitionParsing$$Lambda$68/1446922577.apply(Unknown Source) at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103) at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:103) at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:76) at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71) at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901) at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71) at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67) at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115) at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:196) at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:155) at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135) at org.kframework.kompile.Kompile.run(Kompile.java:121) at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69) at org.kframework.main.FrontEnd.main(FrontEnd.java:52) at org.kframework.main.Main.runApplication(Main.java:113) at org.kframework.main.Main.runApplication(Main.java:103) at org.kframework.main.Main.main(Main.java:52) [Error] Internal: Uncaught exception thrown of type NoSuchElementException. Please rerun your program with the --debug flag to generate a stack trace, and file a bug report at https://github.com/kframework/k/issues (None.get)



dongbiao830415@foxmail.com
 
From: Grigore Rosu
Date: 2017-07-24 12:47
To: runtimeverification/k
CC: dongbiao830415; Author
Subject: Re: [runtimeverification/k] Error while compiling lambda.k (#22)
Remove the `--no-prelude` option and it should work.

Grigore


________________________________

**Comment by dongbiao830415** [comment]
dongbiao830415@foxmail.com
 
From: Grigore Rosu
Date: 2017-07-24 12:49
To: runtimeverification/k
CC: dongbiao830415; Author
Subject: Re: [runtimeverification/k] Error while compiling lambda.k (#22)
If you just want to use kcc, we recommend that you download RV-Match (https://runtimeverification.com/match/) 

Grigore 


________________________________

**Comment by dwightguth** [comment]
Lambda.k is not going to work with this version of K because we do not have support for substitution. The tutorial needs to be cleaned up in the repository to make this clear. If you want to use the tutorial, we recommend using the version of K developed by UIUC.

**Comment by dongbiao830415** [comment]
How big is the difference between the two versions? Why?

Thank you!




dongbiao830415@foxmail.com
 
From: dwightguth
Date: 2017-07-24 23:49
To: runtimeverification/k
CC: dongbiao830415; Author
Subject: Re: [runtimeverification/k] Error while compiling lambda.k (#22)
Lambda.k is not going to work with this version of K because we do not have support for substitution. The tutorial needs to be cleaned up in the repository to make this clear. If you want to use the tutorial, we recommend using the version of K developed by UIUC.

**Comment by dwightguth** [comment]
They have slightly different standard libraries (e.g. substitution is only in one version), slightly different language syntax (although it should be possible to transform procedurally), and runtimeverification/k only has support for concrete execution, but it is several orders of magnitude faster.

We performed the fork in order to maintain more control of the code that Runtime Verification uses in production for rv match.

**Comment by suhabe** [comment]
> If you want to use the tutorial, we recommend using the version of K developed by UIUC.

Where can I find the version of K developed by UIUC? I want to go through the tutorial.

I tired the latest version from this repo, but couldn't get past the error:
```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 6bc147f
Git branch: master
Build date: Tue Jan 01 11:57:44 PST 2019
```
```
$ kompile lambda.k 
[Error] Compiler: Could not find sorts: [Id]
	Source(lambda.k)
	Location(3,18,3,36)
```
```
$ cat lambda.k 
module LAMBDA
  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
endmodule
```

**Comment by dwightguth** [comment]
Long story short we have reintegrated the two parts of K again and it should work with the version of K you are using, but K has changed to no longer implicitly import any modules, so you need to add `imports ID` to your definition of lambda calculus. Alternately, you can just use the versions of the tutorial found in the repository itself, which should be maintained and up to date.
