### ISSUE TITLE
[Bug] [kprovex] - Fails with cryptic error message when backend fails

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2245]
K Version
---------

Tell us what version of K you are using.

Example:

```
+ kompile --version
K version:    v5.1.208-2-g264c3af2b2
Build date:   Fri Oct 01 16:39:34 UTC 2021
```

Description
-----------

Running `kprove` where the LHS of the `<k>` cell looks like `claim <k> (SOMETHING ~> _ => .) ... </k>` causes a cryptic failure in the frontend with the backends output.

Input Files
-----------

File: `test.k`:

```
requires "domains.md"

module TEST
    imports MAP
    imports BOOL

    syntax Foo ::= "a" | "b" | "c"
 // ------------------------------
    rule <k> a => b ... </k>

endmodule

module TEST-SPEC
    imports TEST

    claim <k> (a ~> _ => .) ... </k>
 
endmodule
```

Reproduction Steps:
--------------------

Run `kompile`:

```
+ kompile --main-module TEST --backend haskell test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

Run `kprovex`:

```
+ kprovex test.k --spec-module TEST-SPEC --debug
kore-exec: [221324] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /home/dev/src/k/test.k:16:11-16:37
java.util.NoSuchElementException: key not found: append
        at scala.collection.MapLike.default(MapLike.scala:232)
        at scala.collection.MapLike.default$(MapLike.scala:231)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike.apply(MapLike.scala:141)
        at scala.collection.MapLike.apply$(MapLike.scala:140)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:302)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:296)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.kore.TransformK.apply(TransformK.java:76)
        at org.kframework.kore.TransformK.apply(TransformK.java:15)
        at org.kframework.kore.KTransformer.apply(transformers.scala:15)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.kore.TransformK.apply(TransformK.java:23)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:314)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:296)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.kore.TransformK.apply(TransformK.java:23)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:314)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:296)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:307)
        at org.kframework.unparser.KPrint$2.apply(KPrint.java:296)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.unparser.KPrint.sortCollections(KPrint.java:316)
        at org.kframework.unparser.KPrint.abstractTerm(KPrint.java:199)
        at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:122)
        at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:114)
        at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:110)
        at org.kframework.kprovex.KProve.run(KProve.java:90)
        at org.kframework.kprovex.KProveFrontEnd.run(KProveFrontEnd.java:58)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(NoSuchElementException: key not found: append)
```

This is happenning in the sort collections pass in the term printing it looks like: https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/unparser/KPrint.java#L302. Indeed, if I add `--no-sort-collections`, to `kprovex`, the error changes to a different location (in `KOREToTreeNodes`).

Expected Behavior
-----------------

Either this should be an error in the original proof (maybe there is something weird happenning with parsing I don't understand?), or we should be able to handle this case and get a counterexample state.

**Comment by radumereuta** [comment]
It's trying to pretty print this kore term:
```
#And{GeneratedTopCell}(
  #And{GeneratedTopCell}(
    `<generatedTop>`(
      `<k>`(`a_TEST_Foo`(.KList)~>append(_0,_DotVar1)),
      `<generatedCounter>`(_DotVar2)),
    #Ceil{K,GeneratedTopCell}(append(_0,_DotVar1))),
  #Not{GeneratedTopCell}(
    #Equals{K,GeneratedTopCell}(_DotVar1,`a_TEST_Foo`(.KList)~>append(_0,_DotVar1))))
```
We had similar issues before: #1509 #1682
but I can't figure out where this label is coming from. @ana-pantilie is it possible it's something internal to the haskell backend?

**Comment by ana-pantilie** [comment]
@radumereuta Which label? Also, I'm not sure I follow what you want to do, is the code you posted some simplified kore?

**Comment by radumereuta** [comment]
The front-end of kprove fails when trying to pretty print the term returned by the haskell backend because it can't find any definition for the klabel `append`.
I've looked through domains.md and kast.md and I can't find any such label.

**Comment by ana-pantilie** [comment]
@radumereuta Could [this](https://github.com/kframework/kore/blob/ed422630f9383b2774f1ec8ea04eee86ea0afe1e/src/main/kore/prelude.kore#L10) be it? It's in the backend's `prelude.kore`. I know we use this file for defining the reachability modality aliases, not so sure why those `append`, `kseq` etc. would be specific to the backend, though.

**Comment by radumereuta** [comment]
We need to add a transformation in https://github.com/kframework/k/blob/master/kore/src/main/scala/org/kframework/parser/kore/parser/KoreToK.scala
to transform `append` int KSequence. Basically the inverse of https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L1956

**Comment by ehildenb** [comment]
This is now blocking the KEVM summarizer.

**Comment by SchmErik** [comment]
ok, I'll take a look tomorrow. @ehildenb how urgent is this? I just want to know so I can prioritize..

**Comment by ehildenb** [comment]
Nothing mission critical, but it's blocking my experiments with the summarizer and seems like an easy enough fix.

**Comment by SchmErik** [comment]
Took a look this morning and I found that this pull request https://github.com/kframework/k/pull/2250 causes kprovex to hang on this test case rather than crash... @ana-pantilie or @dopamane do you know what's going on here?

**Comment by ehildenb** [comment]
@SchmErik you can add the option `--haskell-backend-command "kore-exec --bug-report bug.tar.gz" --depth 0` to get the dumped Kore file and command it would execute in `bug.tar.gz`, and you can submit an issue to kframework/kore about it, linking to this issue.

Then they can independently figure out the hang while you work with the older commit to do the unparsing. I guess for this test, it would be best to just run the proof on the older commit (with `--output kore` to get the Kore), then the test you add should just be that calling `kast --input kore --output pretty input.kore` gives the correct output (where `input.kore` will contain the `append` symbol).

**Comment by SchmErik** [comment]
using `--depth 0` stops the program from hanging. So I have a way to proceed with the bug with the current master but I'll file a bug against kore

**Comment by SchmErik** [comment]
> @SchmErik you can add the option `--haskell-backend-command "kore-exec --bug-report bug.tar.gz" --depth 0` to get the dumped Kore file and command it would execute in `bug.tar.gz`, and you can submit an issue to kframework/kore about it, linking to this issue.
> 
> Then they can independently figure out the hang while you work with the older commit to do the unparsing. I guess for this test, it would be best to just run the proof on the older commit (with `--output kore` to get the Kore), then the test you add should just be that calling `kast --input kore --output pretty input.kore` gives the correct output (where `input.kore` will contain the `append` symbol).

@ehildenb I ended up adding test.k as a test case in my pull request here https://github.com/kframework/k/pull/2265/commits/358dcfc72e4ff7431a255835faf2c8199a6fa491#diff-1a000a23cde6aaa261d759b37b8a452142a64be1cf32678588aea61f9471ccb3. Any other value to this option causes kprove to hang but the results are still pretty-printed. When this regression is solved, I was thinking that I can remove the `--depth 0` from the Makefile.

**Comment by ehildenb** [comment]
Great! That looks fine to me, no need to wait for the regression to be fixed.

**Comment by SchmErik** [comment]
@ehildenb what's the actual expected result of this test case? This was fixed in the backend so I run this test without --depth 0 and I get the following output. Is this expected?

```
kore-exec: [167571] Warning (WarnUnsimplifiedCondition):                                                                                                                       [462/1988]
    (InfoReachability) while checking the implication:                                      
    Condition not simplified after 4 rounds.                                                
    Original condition:                                                                     
        \and(                                                                                                                                                                            
            /* term: */                                                                     
            /* D Sfa */ \top{_}(),                                                          
        \and(                                                                                                                                                                            
            /* predicate: */                                                                                                                                                             
            /* Spa */                                                                       
            \and{_}(                                                                                                                                                                     
                /* Spa */                                                                   
                \ceil{SortGeneratedTopCell{}, _}(                                           
                    /* Fn Sfa */                                                            
                    Lbl'-LT-'generatedTop'-GT-'{}(                                          
                        /* Fn Sfa */                                                        
                        Lbl'-LT-'k'-GT-'{}(                                                                                                                                              
                            /* Fn Sfa */                                                                                                                                                 
                            kseq{}(                                                         
                                /* Fl Fn D Sfa Cli */                                       
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(                     
                                    /* Fl Fn D Sfa Cl */                                    
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()                                                                                                                    
                                ),                                                          
                                /* Fn Sfa */                                                
                                append{}(                                                   
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},             
                                    /* Fl Fn D Sfa */                                                                                                                                    
                                    ConfigVar'Unds'DotVar1:SortK{}                          
                                )                                                           
                            )                                                               
                        ),                                                                                                                                                               
                        /* Fl Fn D Sfa */
                        Lbl'-LT-'generatedCounter'-GT-'{}(
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar2:SortInt{}
                        )
                    )
                ),
                /* Sfa */
                \not{_}(
                    /* Spa */
                    \and{_}(
                        /* Sfa */
                        \ceil{SortK{}, _}(
                            /* Fn Sfa */
                            append{}(
                                /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}
                            )
                        ),
                        /* Sfa */
                        \equals{SortK{}, _}(
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},
                            /* Fn Sfa */
                            kseq{}(
                                /* Fl Fn D Sfa Cli */
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                                    /* Fl Fn D Sfa Cl */
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()
                                ),
                                /* Fn Sfa */
                                append{}(
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                    /* Fl Fn D Sfa */
                                    ConfigVar'Unds'DotVar1:SortK{}
                                )
                            )
                        )
                    )
                )
            ),
            /* substitution: */
            \top()
        ))

   Output after 4 rounds:
        \and(
            /* term: */
            /* D Sfa */ \top{_}(),
        \and(
            /* predicate: */
            /* Spa */
            \and{_}(
                /* Sfa */
                \ceil{SortK{}, _}(
                    /* Fn Sfa */
                    append{}(
                        /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                        /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}
                    )
                ),
                /* Spa */
                \not{_}(
                    /* Spa */
                    \and{_}(
                        /* D Sfa */ \top{_}(),
                        /* Spa */
                        \equals{SortK{}, _}(
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},
                            /* Fn Sfa */
                            kseq{}(
                                /* Fl Fn D Sfa Cli */
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                                    /* Fl Fn D Sfa Cl */
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()
                                ),
                                /* Fn Sfa */
                                append{}(
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                    /* Fl Fn D Sfa */
                                    ConfigVar'Unds'DotVar1:SortK{}
                                )
                            )
                        )
                    )
                )
            ),
            /* substitution: */
            \top()
        ))


kore-exec: [181299] Warning (WarnUnsimplifiedCondition):
    (InfoReachability) while checking the implication:
    Condition not simplified after 4 rounds.
    Original condition:
        \and(
            /* term: */
            /* D Sfa */ \top{_}(),
        \and(
            /* predicate: */
            /* Spa */
            \and{_}(
                /* Sfa */
                \ceil{SortK{}, _}(
                    /* Fn Sfa */
                    append{}(
                        /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                        /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}
                    )
                ),
                /* Spa */
                \not{_}(
                    /* Spa */
                    \and{_}(
                        /* D Sfa */ \top{_}(),
                        /* Spa */
                        \equals{SortK{}, _}(
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},
                            /* Fn Sfa */
                            kseq{}(
                                /* Fl Fn D Sfa Cli */
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                                    /* Fl Fn D Sfa Cl */
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()
                                ),
                                /* Fn Sfa */
                                append{}(
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                    /* Fl Fn D Sfa */
                                    ConfigVar'Unds'DotVar1:SortK{}
                                )
                            )
                        )
                    )
                )
            ),
            /* substitution: */
            \top()
        ))
    Output after 4 rounds:                                                                                                                                                     [295/1988]
        \and(
            /* term: */
            /* D Sfa */ \top{_}(),
        \and(
            /* predicate: */
            /* Spa */
            \and{_}(
                /* Sfa */
                \ceil{SortK{}, _}(
                    /* Fn Sfa */
                    append{}(
                        /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                        /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}
                    )
                ),
                /* Spa */
                \not{_}(
                    /* Spa */
                    \and{_}(
                        /* D Sfa */ \top{_}(),
                        /* Spa */
                        \equals{SortK{}, _}(
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},
                            /* Fn Sfa */
                            kseq{}(
                                /* Fl Fn D Sfa Cli */
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                                    /* Fl Fn D Sfa Cl */
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()
                                ),
                                /* Fn Sfa */
                                append{}(
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                    /* Fl Fn D Sfa */
                                    ConfigVar'Unds'DotVar1:SortK{}
                                )
                            )
                        )
                    )
                )
            ),
            /* substitution: */
            \top()
        ))
        
  kore-exec: [194407] Warning (WarnUnsimplifiedCondition):                                    
    (InfoReachability) while checking the implication:                                       
    Condition not simplified after 4 rounds.
    Original condition:
        \and(                     
            /* term: */           
            /* D Sfa */ \top{_}(),
        \and(               
            /* predicate: */
            /* Spa */    
            \and{_}(              
                /* Sfa */         
                \ceil{SortK{}, _}(
                    /* Fn Sfa */                                                            
                    append{}(                                                               
                        /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},                         
                        /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}                     
                    )    
                ),       
                /* Spa */    
                \not{_}(     
                    /* Spa */                 
                    \and{_}(                  
                        /* D Sfa */ \top{_}(),
                        /* Spa */                                                           
                        \equals{SortK{}, _}(                                                
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},                
                            /* Fn Sfa */                                                    
                            kseq{}(                                                         
                                /* Fl Fn D Sfa Cli */                  
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(
                                    /* Fl Fn D Sfa Cl */                                    
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()                        
                                ),          
                                /* Fn Sfa */                                                
                                append{}(                                                   
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},
                                    /* Fl Fn D Sfa */                                       
                                    ConfigVar'Unds'DotVar1:SortK{}                           
                                )
                            )
                        )
                    )
                )              
            ),                 
            /* substitution: */
            \top()        
        ))                
    Output after 4 rounds:
        \and(                     
            /* term: */           
            /* D Sfa */ \top{_}(),
        \and(               
            /* predicate: */
            /* Spa */    
            \and{_}(              
                /* Sfa */         
                \ceil{SortK{}, _}(
                    /* Fn Sfa */                                                            
                    append{}(                                                               
                        /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},                         
                        /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{}                     
                    )    
                ),       
                /* Spa */    
                \not{_}(     
                    /* Spa */                 
                    \and{_}(                  
                        /* D Sfa */ \top{_}(),
                        /* Spa */                                                           
                        \equals{SortK{}, _}(                                                
                            /* Fl Fn D Sfa */ ConfigVar'Unds'DotVar1:SortK{},                
                            /* Fn Sfa */                                                    
                            kseq{}(
                                /* Fl Fn D Sfa Cli */                                        
                                /* Inj: */ inj{SortFoo{}, SortKItem{}}(                      
                                    /* Fl Fn D Sfa Cl */                                     
                                    Lbla'Unds'DEF-SYNTAX'Unds'Foo{}()                        
                                ),
                                /* Fn Sfa */
                                append{}(
                                    /* Fl Fn D Sfa */ ConfigVar'Unds'0:SortK{},              
                                    /* Fl Fn D Sfa */                                        
                                    ConfigVar'Unds'DotVar1:SortK{}                           
                                )
                            )
                        )
                    )
                )
            ),
            /* substitution: */
            \top()
        ))
```

**Comment by ana-pantilie** [comment]
@SchmErik That warning is a direct consequence of the fix, so don't worry about it. Let me know, though, if the test is now failing.
