### ISSUE TITLE
[Bug] [mvn package|kompile] - Issues while installing, building and running K on Apple Silicon

### ISSUE THREAD

**Issue by ACassimiro** [runtimeverification/k#2276]
K Version: v5.1.226-1-g40c4932f6-dirty

Description
-----------

Issues have been found while trying to install the k framework via package, to build with maven and to use the kompile command on Apple Silicon machines (M1 chips). 

 **- INSTALLATION VIA BREW PACKAGE:** 

After installing K using the package available at the release page, an attempt to use the kompile command to build the definitions for the first K program presented in K training lesson 2 returns the following message:

```
dyld: Library not loaded: /opt/homebrew/opt/jemalloc/lib/libjemalloc.2.dylib
 Referenced from: /opt/homebrew/lib/kframework/../../bin/llvm-kompile-codegen
 Reason: no suitable image found. Did find:
    /opt/homebrew/opt/jemalloc/lib/libjemalloc.2.dylib: mach-o, but wrong architecture
    /opt/homebrew/Cellar/jemalloc/5.2.1_1/lib/libjemalloc.2.dylib: mach-o, but wrong architecture
/opt/homebrew/lib/kframework/../../bin/llvm-kompile: line 44: 9377 Abort trap: 6     "$(dirname "$0")"/llvm-kompile-codegen "$definition" "$dt_dir"/dt.yaml "$dt_dir" $debug > "$mod"
[Error] Critical: llvm-kompile returned nonzero exit code: 134
Examine output to see errors.
```
  
[Jemalloc supports Apple Silicon](https://formulae.brew.sh/formula/jemalloc), which leads me to believe that it must be something related to how the K release package has been built.

 **- BUILDING WITH MAVEN:**

When building with maven, errors were be triggered in the stage "K Framework LLVM Backend". The errors are related to the llvm 13, which, from my understanding, is not supported to build the K framework. To solve this issue, an earlier version of llvm must be installed. I've solved this using brew's llvm@12 package.

After doing so, I still could not successfully build the project as many of the libraries which have been installed as dependencies could not be found. The error messages are as follows: 

![image](https://user-images.githubusercontent.com/5834739/137825071-244716bf-55f1-40ca-9675-1e8f6033c890.png)

This issue seems to be related to the change in brew's default installation directory, as packages are now being installed in the /opt/homebrew/ subfolders. A workaround to this problem is to create a symbolic link from the /opt/homebrew/lib, /opt/homebrew/include, and /opt/homebrew/bin to the /usr/local/ folder. This can be done using the following commands:

```
cd /usr/local/
sudo ln -s /opt/homebrew/lib lib
sudo ln -s /opt/homebrew/include include
sudo ln -s /opt/homebrew/bin bin
```

After adding the symbolic links, the libraries could be found during the building process. Still, the following error would be triggered in the llvm backend building stage:

`[exec] /Users/acassimiro/Documents/tools/k/llvm-backend/src/main/native/llvm-backend/runtime/meta/ffi.cpp:241:11: error: enumeration value ‘FFI_BAD_ARGTYPE’ not handled in switch [-Werror,-Wswitch]`

Which was fixed after adding `case FFI_BAD_ARGTYPE: throw std::invalid_argument(“Bad argument type”); break;` to the k/llvm-backend/src/main/native/llvm-backend/runtime/meta/ffi.cpp file on line 247.

With this, I've managed to successfully build K using `mvn package -DskipTests`, but I still cannot execute the kompile command.

 **- EXECUTING KOMPILE WITH THE BINARIES GENERATED AFTER COMPILING FROM THE SOURCE:**

Finally, after building K, the following error is shown after trying to call compile on a simple K file:

```
ld: warning: ignoring file tmp.bN8Tml3rEu/equality.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64ld: warning: ignoring file tmp.bN8Tml3rEu/asm.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64

ld: warning: ignoring file tmp.bN8Tml3rEu/finish_rewriting.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/fresh.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/move_int.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/getTag.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/string_equal.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/take_steps.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file tmp.bN8Tml3rEu/move_float.ll.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_evaluateFunctionSymbol", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
  "_finish_rewriting", referenced from:
      _main in main-1610ae.o
  "_first_inj_tag", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
  "_getBlockHeaderForSymbol", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
  "_getInjectionForSortOfTag", referenced from:
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
  "_getLayoutData", referenced from:
      _koreCollect in libcollect.a(collect.cpp.o)
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
      debruijnizeInternal(block*) in libmeta.a(substitution.cpp.o)
      replaceBinderInternal(block*) in libmeta.a(substitution.cpp.o)
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
      _incrementDebruijn in libmeta.a(substitution.cpp.o)
      _debruijnize in libmeta.a(substitution.cpp.o)
      ...
  "_getSymbolNameForTag", referenced from:
      _printConfigurationInternal in libutil.a(ConfigurationPrinter.cpp.o)
  "_getTagForSymbolNameInternal", referenced from:
      _getTagForSymbolName in libutil.a(ConfigurationParser.cpp.o)
  "_getToken", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
  "_get_gc_threshold", referenced from:
      _is_collection in libcollect.a(collect.cpp.o)
  "_hook_KEQUAL_eq", referenced from:
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
      _hook_LIST_in in libcollections.a(lists.cpp.o)
      immer::detail::rbts::rrbtree<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>::equals(immer::detail::rbts::rrbtree<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> const&) const in libcollections.a(lists.cpp.o)
      bool immer::detail::rbts::equals_visitor::visit_leaf<immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&>(immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&, unsigned long) in libcollections.a(lists.cpp.o)
      bool immer::detail::rbts::equals_visitor::visit_leaf<immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::relaxed_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&>(immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::relaxed_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&, unsigned long) in libcollections.a(lists.cpp.o)
      bool immer::detail::rbts::equals_visitor::visit_leaf<immer::detail::rbts::full_leaf_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&>(immer::detail::rbts::full_leaf_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::leaf_sub_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&, unsigned long) in libcollections.a(lists.cpp.o)
      bool immer::detail::rbts::equals_visitor::visit_leaf<immer::detail::rbts::full_leaf_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::relaxed_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&>(immer::detail::rbts::full_leaf_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::relaxed_pos<immer::detail::rbts::node<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u> >&, immer::detail::rbts::rrbtree_iterator<KElem, immer::memory_policy<immer::heap_policy<kore_alloc_heap>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5u, 5u>&, unsigned long) in libcollections.a(lists.cpp.o)
      ...
  "_isSymbolABinder", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
      debruijnizeInternal(block*) in libmeta.a(substitution.cpp.o)
      replaceBinderInternal(block*) in libmeta.a(substitution.cpp.o)
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
      _incrementDebruijn in libmeta.a(substitution.cpp.o)
      _printConfigurationInternal in libutil.a(ConfigurationPrinter.cpp.o)
  "_isSymbolAFunction", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
      substituteInternal(block*) in libmeta.a(substitution.cpp.o)
  "_last_inj_tag", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
  "_move_float", referenced from:
      _hook_STRING_string2float in libstrings.a(strings.cpp.o)
      _hook_FLOAT_ceil in libarithmetic.a(float.cpp.o)
      _hook_FLOAT_floor in libarithmetic.a(float.cpp.o)
      _hook_FLOAT_trunc in libarithmetic.a(float.cpp.o)
      _hook_FLOAT_round in libarithmetic.a(float.cpp.o)
      _hook_FLOAT_int2float in libarithmetic.a(float.cpp.o)
      _hook_FLOAT_sin in libarithmetic.a(float.cpp.o)
      ...
  "_move_int", referenced from:
      _hook_STRING_ord in libstrings.a(strings.cpp.o)
      _hook_STRING_find in libstrings.a(strings.cpp.o)
      _hook_STRING_rfind in libstrings.a(strings.cpp.o)
      _hook_STRING_findChar in libstrings.a(strings.cpp.o)
      _hook_STRING_rfindChar in libstrings.a(strings.cpp.o)
      _hook_STRING_string2base_long in libstrings.a(strings.cpp.o)
      _hook_STRING_countAllOccurrences in libstrings.a(strings.cpp.o)
      ...
  "_output_file", referenced from:
      _main in main-1610ae.o
  "_set_gc_threshold", referenced from:
      _koreCollect in libcollect.a(collect.cpp.o)
  "_sort_table", referenced from:
     -u command line option
  "_statistics", referenced from:
      _main in main-1610ae.o
  "_storeSymbolChildren", referenced from:
      _parseConfiguration in libutil.a(ConfigurationParser.cpp.o)
  "_take_steps", referenced from:
      _main in main-1610ae.o
  "_visitChildren", referenced from:
      _printConfigurationInternal in libutil.a(ConfigurationPrinter.cpp.o)
ld: symbol(s) not found for architecture arm64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
[Error] Critical: llvm-kompile returned nonzero exit code: 1
Examine output to see errors.
[Warning] Compiler: Could not find main syntax module with name
LESSON-02-A-SYNTAX in definition.  Use --syntax-module to specify one. Using
LESSON-02-A as default.
```

I'm still looking for a workaround for this lasts issue.

Input Files
-----------

The input file used was the [first K example provided in the K-tutorial second lesson](https://github.com/kframework/k/tree/master/k-distribution/k-tutorial/1_basic/02_basics).  

Reproduction Steps
------------------

Installation via brew package was done following the instructions provided in the K-framework release page.

Building with maven was done with `mvn package -DskipTests`.

The kompilation attempt was done with `kompile lesson-02-a.k`.

Expected Behavior
-----------------

With the instructions available in the release page and the git's README information, I expected to be able to successfully install the K-framework with no issues in its functionalities.

**Comment by dwightguth** [comment]
Most likely, the last error you list there will have to be solved by changing the target triple listed in all the llvm ir we use to match the target triple corresponding to the target platform of the compiler. This should also address the target triple warnings we sometimes get that we just suppress. It's a more involved code change, but we'd have to actually buy an m1 mac for me to test on in order to actually develop the change since our current vm-based approach isn't powerful enough to do aarch64 development, and the change is complicated enough I don't want to have to do back and forth.

I'm sure we'll address this eventually, since my understanding is that Apple intends to eventually completely phase out x86_64 chips, and people will continue to want to run k on MacOS, but I can't give any kind of timeline here right now of when I could work on this.

It sounds like you've done very good work here identifying what the main problems will be, so if you want to contribute fixes for these issues to the llvm backend, I'd be happy to help you through the process. If you don't, you're probably going to need to find a x86_64 machine to do development on instead though, at least for right now.

**Comment by Baltoli** [comment]
The brew package error is probably expected behaviour for the moment - we don't package an ARM bottle of K yet, but when we do it should be possible to install using Homebrew.

**Comment by Baltoli** [comment]
@ACassimiro by way of the LLVM target triple issue, the likely fix Dwight suggests is to change the [target triple lines](https://github.com/kframework/llvm-backend/blob/master/runtime/equality.ll#L2) in all the `.ll` files to whatever the output of `llvm-config --host-target` is on your system. I don't have an M1 mac either so I can't test it, unfortunately.

[This CMake stanza](https://github.com/kframework/llvm-backend/blob/1943e4f66ee59efa8649af7474f3db3a674560e4/CMakeLists.txt#L31-L40) also looks like it might prove problematic for you.

**Comment by dwightguth** [comment]
For clarity's sake, if you're going to modify your working copy as a workaround, the files you need to modify are all the .ll files in the llvm-backend repository, as well as the string literal with llvm code at the top of `lib/codegen/CreateTerm.cpp`.

**Comment by ACassimiro** [comment]
Thanks for the help, Dwight, Bruce!

I believe I've made the necessary changes with regards to the references to the target architecture, but I'm still getting failures with krun or when trying to build with tests.

After building with the -X option, I'm getting this output:

```
Tests run: 142, Failures: 0, Errors: 41, Skipped: 0, Time elapsed: 0.05 sec <<< FAILURE! - in org.kframework.compile.ConstantFoldingTest
testFloatAbs(org.kframework.compile.ConstantFoldingTest)  Time elapsed: 0.023 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no mpfr_java in java.library.path: /Users/acassimiro/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:., /private/var/folders/3g/m0vx317j0cv3scbys3kzbc0r0000gn/T/libmpfr_java-64-15869754420578430758.jnilib: dlopen(/private/var/folders/3g/m0vx317j0cv3scbys3kzbc0r0000gn/T/libmpfr_java-64-15869754420578430758.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/3g/m0vx317j0cv3scbys3kzbc0r0000gn/T/libmpfr_java-64-15869754420578430758.jnilib: no matching architecture in universal wrapper
	/private/var/folders/3g/m0vx317j0cv3scbys3kzbc0r0000gn/T/libmpfr_java-64-15869754420578430758.jnilib: no matching architecture in universal wrapper]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.kframework.mpfr.mpfr.<clinit>(mpfr.java:47)
	at org.kframework.mpfr.mpfr$mpfr_t.<clinit>(mpfr.java:487)
	at org.kframework.mpfr.BigFloat.<init>(BigFloat.java:300)
	at org.kframework.mpfr.BigFloat.<init>(BigFloat.java:320)
	at org.kframework.mpfr.BigFloat.<clinit>(BigFloat.java:426)
	at org.kframework.compile.ConstantFoldingTest._double(ConstantFoldingTest.java:784)
	at org.kframework.compile.ConstantFoldingTest.testUnaryOp(ConstantFoldingTest.java:817)
	at org.kframework.compile.ConstantFoldingTest.testFloatAbs(ConstantFoldingTest.java:880)

testFloatAdd(org.kframework.compile.ConstantFoldingTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.kframework.mpfr.BigFloat
	at org.kframework.compile.ConstantFoldingTest._double(ConstantFoldingTest.java:784)
	at org.kframework.compile.ConstantFoldingTest.testBinaryOp(ConstantFoldingTest.java:826)
	at org.kframework.compile.ConstantFoldingTest.testFloatAdd(ConstantFoldingTest.java:865)

testFloatDiv(org.kframework.compile.ConstantFoldingTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.kframework.mpfr.BigFloat
	at org.kframework.compile.ConstantFoldingTest._double(ConstantFoldingTest.java:784)
	at org.kframework.compile.ConstantFoldingTest.testBinaryOp(ConstantFoldingTest.java:826)
	at org.kframework.compile.ConstantFoldingTest.testFloatDiv(ConstantFoldingTest.java:855)

testFloatMul(org.kframework.compile.ConstantFoldingTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.kframework.mpfr.BigFloat
	at org.kframework.compile.ConstantFoldingTest._double(ConstantFoldingTest.java:784)
	at org.kframework.compile.ConstantFoldingTest.testBinaryOp(ConstantFoldingTest.java:826)
	at org.kframework.compile.ConstantFoldingTest.testFloatMul(ConstantFoldingTest.java:850)

...
```

It seems like all the 41 errors are related to the mpfr library. What I'm trying to do right now is to generate a library from the [mpfr-java](https://github.com/kframework/mpfr-java) repository and to place it on my libraries folder.

Do you see a more appropriate way to fix this?

**Comment by Baltoli** [comment]
Not sure on the MPFR issue, but it's good to see that the target architecture change fixes your initial problem. I'm taking a look at supporting apple silicon properly across our projects now, so will investigate that issue when I get to the K frontend - sorry not to be more immediately helpful!

**Comment by dwightguth** [comment]
I would ignore the MPFR issue for now if you can. That code is deployed in the form of a jar that contains native code bundled into it, and we obviously didn't anticipate ARM macs when we bundled that code a long time ago. It's fixable, but it would involve us basically tweaking all that code to account for the ARM Macs. You can just run `mvn package -DskipTests` to skip the unit tests. What is the error you get when you run krun?

**Comment by ACassimiro** [comment]
No worries @Baltoli, thank you for the help!

@dwightguth, if I skip the tests I'm able to kompile without issues, but when I run krun I get the following output:

```
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoClassDefFoundError: Could not initialize class
org.fusesource.jansi.internal.CLibrary)
```

Do you think the error messages regarding the MPFR java library has something to do with this?

**Comment by dwightguth** [comment]
Can you rerun `krun` with the `--debug` flag? I'd like to see the stack trace.

**Comment by dwightguth** [comment]
It does seem to be related to the MPFR library, but I don't understand why that class would get loaded by the code path you are using, so I'd like to understand better exactly what is triggering the error.

**Comment by ACassimiro** [comment]
I'm not sure if I'm making this right, but it seems like I cannot use the `--debug` flag on krun. Here is how I'm doing:

```
krun --debug input.color 
```
Outputs:
```
Usage: krun [PROGRAM] [-cNAME=VALUE] [-d DIR]
Execute a program using a K semantics that was built with kompile.

Mandatory arguments to long options are mandatory for short options too.

krun expects 0 or 1 positional arguments. If a positional argument is present,
it must be a file and the contents of that file is parsed using the parser
specified with --parser and used as the value of $PGM (unless --term is
present; see below).
 
...
```

input.color is a file with the following content:

```
colorOf(Banana())
```

Could you please specify where I can place the --debug flag for krun?

**Comment by dwightguth** [comment]
Ah. We probably need to modify the script to propagate the values. Can you pass `-v --save-temps` to krun, look at the last command that krun invokes prior to the crash, and pass --debug to that command?

**Comment by ACassimiro** [comment]
Running `krun -v --save-temps input.color` I get:

```
+ kparse --directory . input.color
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoClassDefFoundError: Could not initialize class
org.fusesource.jansi.internal.CLibrary)
```

It seems like I can't use --debug in `kparse` as well, and neither run `+ kparse --directory . input.color` with the `--save-temps`, as I receive a `[Error] Critical: You can only parse one program at a time.` message. Running `kparse --directory . input.color --verbose` I get:

```
+ /Users/acassimiro/Documents/tools/k/k-distribution/target/release/k/bin/kast --output kore --directory . input.color --verbose
Parse command line options                                   =  0.007s
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoClassDefFoundError: Could not initialize class
org.fusesource.jansi.internal.CLibrary)
```

I see it is crashing when calling `kast`, and I can use the `--debug` flag on it. This is what I get when running `kast --output kore --directory . input.color --verbose --debug`: 

```
Parse command line options                                   =  0.007s
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoClassDefFoundError: Could not initialize class
org.fusesource.jansi.internal.CLibrary)
acassimiro@Aellisons-MacBook-Pro 02_basics % kast --output kore --directory . input.color --verbose --debug
Parse command line options                                   =  0.006s
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.CLibrary
        at org.kframework.utils.inject.CommonModule.ttyInfo(CommonModule.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:250)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:147)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError
(NoClassDefFoundError: Could not initialize class
org.fusesource.jansi.internal.CLibrary)
```

**Comment by ehildenb** [comment]
No satisfactory solution currently other than just "use Nix".

**Comment by goodlyrottenapple** [comment]
@PetarMax reports he's successfully installed K on an M1 mac without nix and uses it daily. Not sure if we need to update any specific install instructions for the M1?

**Comment by ehildenb** [comment]
I think we can close this for now, several people are reporting that it's working on their M1s now.
