### ISSUE TITLE
Fix fragile test-pyk tests

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#2675]
A test that breaks every time the module structure of the K prelude is ever changed is much too fragile; the test needs to be made less fragile so we are not constantly updating output files, completely defeating the purpose of the test.

**Comment by radumereuta** [comment]
Which test is that? And what did you do to make it fail?

**Comment by dwightguth** [comment]
It was in https://github.com/runtimeverification/k/tree/master/pyk/pyk-tests

**Comment by dwightguth** [comment]
The test fails if the module structure of the k prelude is significantly altered in any way, such as by adding an import to a module or splitting one module into two.

**Comment by radumereuta** [comment]
We can try and do it with `--no-prelude` to make it more stable to changes to domains.md.
Add a few extra modules to the test to make sure the import structure is stored correctly.

We could also turn it into a python unit test which takes as input dummy modules.
This way we at least test the functionality.

@tothtamas28 do you have time to take a look at this?

**Comment by tothtamas28** [comment]
> We can try and do it with --no-prelude to make it more stable to changes to domains.md.

Is this viable? The kompiler seems to require these files to exist:
https://kframework.org/k-distribution/include/kframework/builtin/prelude/

```
$ kompile a.k --backend haskell --no-prelude --emit-json --debug
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:529)
        at scala.None$.get(Option.scala:527)
        at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:216)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:240)
        at org.kframework.kompile.Kompile.run(Kompile.java:140)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:78)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(NoSuchElementException: None.get)
```

For now, I will proceed by checking only the subgraph induced by user defined modules, instead of the whole dependency graph.
