### ISSUE TITLE
[Bug] [kast] - Dies with bad error message when passed non-existent sort

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2776]
K Version
---------

```
$ kompile --version
8c77c9792b
```

Description
-----------

Calling `kast --sort ...` with a sort that doesn't exist causes crash with no useful error message.

Input Files
-----------

File `test.k`:

```
module TEST-SYNTAX
  imports BOOL-SYNTAX
  imports INT-SYNTAX

  syntax Pgm ::= Pgm "+" Pgm | Int
endmodule

module TEST
  imports TEST-SYNTAX

  syntax KResult ::= Int | Bool
  syntax KItem   ::= Pgm

  configuration <k> $PGM:Pgm </k>
endmodule
```

File `add.aexp`:

```
3 + 4
```

Reproduction Steps
------------------

`kompile` and then call `kast` on a sort that doesn't exist (`Foo`):

```
+ kompile --backend haskell test.k --output-definition test-kompiled
+ kast add.aexp --definition test-kompiled --sort Foo --debug
java.lang.NullPointerException
        at org.kframework.parser.inner.kernel.EarleyParser.getProductions(EarleyParser.java:645)
        at org.kframework.parser.inner.kernel.EarleyParser.<init>(EarleyParser.java:603)
        at org.kframework.parser.inner.ParseInModule.getParser(ParseInModule.java:165)
        at org.kframework.parser.inner.ParseInModule.parseStringTerm(ParseInModule.java:219)
        at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:193)
        at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:157)
        at org.kframework.kompile.CompiledDefinition.parseSingleTerm(CompiledDefinition.java:204)
        at org.kframework.parser.KRead.prettyRead(KRead.java:66)
        at org.kframework.parser.KRead.prettyRead(KRead.java:54)
        at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:135)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)
```

Expected Behavior
-----------------

`kast` should produce an error message that sort `Foo` doesn't exist.

**Comment by ehildenb** [comment]
This is not blocking, was just very difficult to debug.

**Comment by radumereuta** [comment]
I had a look and this can easily be fixed by adding a test in [ParseInModule](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/parser/inner/ParseInModule.java#L219), or [KRead](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/parser/KRead.java#L54) or [CompiledDefinition](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kompile/CompiledDefinition.java#L204)

But there is a problem with kserver which yields flaky tests.
I suspect something is not wired correctly by our injection system.

```java
        if (!parsingModule.definedSorts().contains(startSymbol.head())) {
            throw KEMException.innerParserError("Could not find start symbol: " + startSymbol, source, Location.apply(startLine, startColumn, startLine, startColumn + 1));
        }

```

**Comment by radumereuta** [comment]
Try to check in the KastFronEnd maybe tests will pass this way.
