### ISSUE TITLE
[K-Bug] Uncaught IndexOutOfBoundsException when configuration has Map cell collection with .Bag

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3227]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v5.5.139

### Operating System

MacOS (Intel)

### K Definitions (If Possible)

```
module BAD
  configuration
    <cells>
      <cell multiplicity="*" type="Map">
        .Bag
      </cell>
    </cells>
endmodule
```

### Steps to Reproduce

1. `kompile --syntax-module BAD --debug bad.k`
2. Note the uncaught IndexOutOfBoundException:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.kframework.compile.GenerateSentencesFromConfigDecl.computeSentencesOfWellFormedCell(GenerateSentencesFromConfigDecl.java:481)
	at org.kframework.compile.GenerateSentencesFromConfigDecl.genInternal(GenerateSentencesFromConfigDecl.java:107)
	at org.kframework.compile.GenerateSentencesFromConfigDecl.genInternal(GenerateSentencesFromConfigDecl.java:103)
	at org.kframework.compile.GenerateSentencesFromConfigDecl.gen(GenerateSentencesFromConfigDecl.java:65)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$26(DefinitionParsing.java:395)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at scala.collection.convert.Wrappers$IteratorWrapper.forEachRemaining(Wrappers.scala:31)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$29(DefinitionParsing.java:396)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:78)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:73)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:69)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:112)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:405)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:293)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:231)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:281)
	at org.kframework.kompile.Kompile.run(Kompile.java:150)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:78)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:119)
	at org.kframework.main.Main.runApplication(Main.java:109)
	at org.kframework.main.Main.main(Main.java:57)
[Error] Internal: Uncaught exception thrown of type IndexOutOfBoundsException
(IndexOutOfBoundsException: Index 0 out of bounds for length 0)
```

### Expected Results

We should emit a more specific error message rather than let the exception reach the user

**Comment by radumereuta** [comment]
The problem comes from https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java#L481
The kompiler tries to generate productions for cell manipulation, and it assumes that a cell of type map contains at least one child cell.
I would add an error message saying that "Cells of type Map expect at least one child cell as its key".

While you are at it, you should also try to add location information to the exception thrown at line 471. Something like this:
```
throw KEMException.compilerError("Unexpected type " + type + " for multiplicity * cell: " + cellName
        + ". Should be one of: Set, Bag, List, Map", KApply(KLabel("#EmptyK"), Seq(), configAtt));
```

The last thing to do is to add a regression test in `regression-new/checks`
Let me know when you start working on this. There is quite an elaborate setup process that makes working on the java code a lot easier.
