### ISSUE TITLE
[K-Bug] "Internal: Uncaught exception thrown of type NoSuchElementException" while parsing

### ISSUE THREAD

**Issue by jeanas** [runtimeverification/k#3446]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [X] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v5.6.90

### Operating System

Linux

### K Definitions (If Possible)

`lambda.k`:

```
module LAMBDA
  import DOMAINS
  
  syntax Lambda ::=
    Id
    | "(" Lambda ")" [bracket]
    > left: Lambda Lambda
    > "/\\\\" Id "." Lambda

endmodule
```

### Steps to Reproduce

```
$ kompile --debug lambda.k
[Warning] Compiler: Could not find main syntax module with name LAMBDA-SYNTAX
in definition.  Use --syntax-module to specify one. Using LAMBDA as default.
$ cat bad.lambda # note the missing ending parenthesis
(/\\ x . const)
  ((/\\ x . x x) (/\\ x . x x)
$ kast bad.lambda
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(NoSuchElementException: No value present)
```

### Expected Results

No internal error.

**Comment by Baltoli** [comment]
```console
$ kast bad.lambda --debug
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.kframework.utils.errorsystem.KException.getSourceLine(KException.java:226)
	at org.kframework.utils.errorsystem.KException.getSourceLineText(KException.java:206)
	at org.kframework.utils.errorsystem.KException.<init>(KException.java:74)
	at org.kframework.utils.errorsystem.KException.<init>(KException.java:56)
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:143)
	at org.kframework.utils.errorsystem.KEMException.innerParserError(KEMException.java:96)
	at org.kframework.parser.inner.kernel.EarleyParser.parseError(EarleyParser.java:890)
	at org.kframework.parser.inner.kernel.EarleyParser.parse(EarleyParser.java:851)
	at org.kframework.parser.inner.ParseInModule.parseStringTerm(ParseInModule.java:237)
	at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:200)
	at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:165)
	at org.kframework.kompile.CompiledDefinition.parseSingleTerm(CompiledDefinition.java:201)
	at org.kframework.parser.KRead.prettyRead(KRead.java:67)
	at org.kframework.parser.KRead.prettyRead(KRead.java:55)
	at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:213)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:115)
	at org.kframework.main.Main.runApplication(Main.java:105)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(NoSuchElementException: No value present)
```

**Comment by Baltoli** [comment]
Looks like an off-by-one error of some kind when we try to get the error location at EOF.

**Comment by Baltoli** [comment]
@dwightguth reports that this is likely actually a bug in the `^~~~~~` printing code, based on the stack trace. Possibly just doesn't have a case to handle when the error is at the end of the file.
