### ISSUE TITLE
[K-Bug] NullPointerException when a symbolic/concrete main module mismatches with the backend

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3486]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v5.6.115

### Operating System

Linux

### K Definitions (If Possible)

`test.k`
```
module TEST-SYMBOLIC [symbolic]
endmodule

module TEST-CONCRETE [concrete]
endmodule
```

### Steps to Reproduce

Either of the following result in a `NullPtrException`:
- `kompile test.k --backend llvm --main-module TEST-SYMBOLIC --syntax-module TEST-SYMBOLIC`
- `kompile test.k --backend haskell --main-module TEST-CONCRETE --syntax-module TEST-CONCRETE`

The stack trace is:
```
java.lang.NullPointerException
	at org.kframework.kompile.DefinitionParsing.lambda$resolveConfigBubbles$20(DefinitionParsing.java:369)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:78)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:73)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$2(transformers.scala:74)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:53)
	at scala.collection.SetLike.map(SetLike.scala:105)
	at scala.collection.SetLike.map$(SetLike.scala:105)
	at scala.collection.AbstractSet.map(Set.scala:53)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:74)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:73)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:69)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:112)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:370)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:290)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:229)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:293)
	at org.kframework.kompile.Kompile.run(Kompile.java:152)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:78)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:115)
	at org.kframework.main.Main.runApplication(Main.java:105)
	at org.kframework.main.Main.main(Main.java:53)
```

### Expected Results

An appropriate error message such as:

- `[Error] Compiler: Main module cannot be marked [symbolic] when using the LLVM backend`
- `[Error] Compiler: Main module cannot be marked [concrete] when using the Haskell backend`

**Comment by radumereuta** [comment]
There are two places where we need to validate the definition if it's loading the correct modules:
https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L160
and
https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L217

One of them is the entry point for kompile and the other one is for kprove.

If you use it on an imported module, it silently drops it. But for the main module, it should not crash with a stack trace; better use a nicer error message. The same happens for the main syntax module.
