### ISSUE TITLE
[K-Bug] failure of producing output in 'program' format for krun in KMIR project

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/k#3861]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v6.1.41

### Operating System

MacOS (Intel)

### Steps to Reproduce

Clone KMIR project at  
```sh
git clone git@github.com:runtimeverification/mir-semantics.git
git checkout  refactor/dir-structure
cd mir-semantics/kmir
make build
source set_env.sh
```
using `kmir run` to test an example:

```sh
poetry run kmir run ../demo/arithm-simple.mir --output program --debug
```
```
INFO 2023-12-08 10:39:36,053 kmir.kmir - Running: /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm/parser_Mir_MIR-SYNTAX ../demo/arithm-simple.mir
INFO 2023-12-08 10:39:36,059 kmir.kmir - Completed in 0.005s with status 0: /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm/parser_Mir_MIR-SYNTAX ../demo/arithm-simple.mir
INFO 2023-12-08 10:39:36,065 pyk.utils - Running: /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm/interpreter /dev/stdin -1 /dev/stdout
INFO 2023-12-08 10:39:36,092 pyk.utils - Completed in 0.027s with status 0: /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm/interpreter /dev/stdin -1 /dev/stdout
INFO 2023-12-08 10:39:36,100 pyk.utils - Running: kore-print /var/folders/r8/1z6nnty91gv06skycppv61l40000gn/T/tmpjyb0469w --definition /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm --output program
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(AssertionError: null)
[Error] kore-print:
/nix/store/lk9wxwzf4zd7aq0cld0zm2sddashrn3j-k-6.1.41-2c4429696d1e053d80c8bfa69b0
d9e85d78cc822/bin-unwrapped/kast --input kore
/var/folders/r8/1z6nnty91gv06skycppv61l40000gn/T/tmpjyb0469w --definition
/Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm --output
program
INFO 2023-12-08 10:39:40,649 pyk.utils - Completed in 4.549s with status 1: kore-print /var/folders/r8/1z6nnty91gv06skycppv61l40000gn/T/tmpjyb0469w --definition /Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm --output program
Traceback (most recent call last):
  File "/Users/emma/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/bin/kmir", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/emma/Documents/tools/mir-semantics/kmir/src/kmir/__main__.py", line 28, in main
    execute(**vars(args))
  File "/Users/emma/Documents/tools/mir-semantics/kmir/src/kmir/__main__.py", line 96, in exec_run
    run(kmir, mir_file, depth=depth, output=output)
  File "/Users/emma/Documents/tools/mir-semantics/kmir/src/kmir/run.py", line 54, in run
    print(kore_print(run_result_kore, kmir.llvm_dir, PrintOutput(output)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emma/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kore/tools.py", line 42, in kore_print
    run_res = run_process(['kore-print', f.name, '--definition', str(definition_dir), '--output', output.value])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emma/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/utils.py", line 421, in run_process
    res.check_returncode()
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('kore-print', '/var/folders/r8/1z6nnty91gv06skycppv61l40000gn/T/tmpjyb0469w', '--definition', '/Users/emma/Documents/tools/mir-semantics/kmir/kdist/v6.1.41/llvm', '--output', 'program')' returned non-zero exit status 1.
```

### Expected Results

There might be three options:
1. Output the `arithm-simple.mir`;
2.  the `init_config` of `arithm-simple.mir`.
`init_config`: https://github.com/runtimeverification/mir-semantics/blob/ad120663684b23b9d1097b87ea6829dde183b068/kmir/src/kmir/kmir.py#L92
3. Disable the `program` output choice for `kmir run`

Prefer option 2.

**Comment by Baltoli** [comment]
The issue here is that you're using the `program` unparsing mode to unparse a term that's actually a complete configuration; what you probably want to use instead is the `pretty` mode which will print all the cells:
```console
$ poetry run kmir run ../demo/arithm-simple.mir --output pretty --debug
INFO 2024-01-22 12:10:35,930 kmir.kmir - Running: /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm/parser_Mir_MIR-SYNTAX ../demo/arithm-simple.mir
INFO 2024-01-22 12:10:35,932 kmir.kmir - Completed in 0.002s with status 0: /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm/parser_Mir_MIR-SYNTAX ../demo/arithm-simple.mir
INFO 2024-01-22 12:10:35,934 kmir.kmir - Running: /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm/interpreter /dev/stdin -1 /dev/stdout
INFO 2024-01-22 12:10:35,940 kmir.kmir - Completed in 0.006s with status 0: /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm/interpreter /dev/stdin -1 /dev/stdout
INFO 2024-01-22 12:10:35,941 pyk.utils - Running: kore-print /dev/stdin --definition /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm --output pretty --color on
INFO 2024-01-22 12:10:35,986 pyk.utils - Completed in 0.045s with status 0: kore-print /dev/stdin --definition /Users/brucecollie/code/mir-semantics/kmir/kdist/v6.1.76-0-gecd6666499/llvm --output pretty --color on
<generatedTop>
  <k>
    #halt ~> .
  </k>
  <returncode>
    0
  </returncode>
  <mir>
    <simulator>
      <callStack>
        .List
      </callStack>
      <currentBasicBlock>
        1
      </currentBasicBlock>
      <phase>
        Finalization
      </phase>
    </simulator>
    <data>
      <functions>
        <function>
          <fnKey>
            Fn ( main :: .FunctionPath )
          </fnKey>
          <localDecls>
            <localDecl>
              <index>
                _0
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                ( )
              </ty>
              <value>
                Unit
              </value>
            </localDecl> <localDecl>
              <index>
                _1
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                bool
              </ty>
              <value>
                true
              </value>
            </localDecl> <localDecl>
              <index>
                _2
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                usize
              </ty>
              <value>
                2
              </value>
            </localDecl> <localDecl>
              <index>
                _3
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                usize
              </ty>
              <value>
                2
              </value>
            </localDecl> <localDecl>
              <index>
                _4
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                usize
              </ty>
              <value>
                4
              </value>
            </localDecl> <localDecl>
              <index>
                _5
              </index>
              <mutability>
                Not
              </mutability>
              <internal>
                false
              </internal>
              <ty>
                usize
              </ty>
              <value>
                2
              </value>
            </localDecl>
          </localDecls>
          <basicBlocks>
            <basicBlock>
              <bbName>
                0
              </bbName>
              <bbBody>
                { _2 = Add ( const 1_usize , const 1_usize ) ;  _3 = Sub ( const 5_usize , const 3_usize ) ;  _4 = Mul ( _2 , _3 ) ;  _5 = Div ( _4 , const 2_usize ) ;  _1 = Eq ( _5 , const 2_usize ) ;  .Statements assert ( _1 , "generator resumed after completion" ) -> bb1  ; }
              </bbBody>
            </basicBlock> <basicBlock>
              <bbName>
                1
              </bbName>
              <bbBody>
                { _0 = const ( ) ;  .Statements return ; }
              </bbBody>
            </basicBlock>
          </basicBlocks>
        </function>
      </functions>
    </data>
  </mir>
</generatedTop>
```

The `program` mode only applies to terms that are _input_ to the semantics; the documentation could and should be clearer in this respect. I will open an issue to track the more specific problem.

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/k/issues/3919 for the specific error tracking; for MIR specifically I would disallow the `--program` mode for outputs from your test cases.

**Comment by yanliu18** [comment]
> #3919 for the specific error tracking; for MIR specifically I would disallow the `--program` mode for outputs from your test cases.

Disable the `program` mode is OK for me.
It seems I have a misunderstanding of the `program` option that I though it would unparse back to mir.

Thanks for looking into it.

**Comment by Baltoli** [comment]
It _will_ do that @yanliu18, but only reliably for the contents of the K cell[^1] - if you wanted to unparse back to MIR using this mode, you could write a Pyk function to grab the K cell and pass the contents to the unparser.

[^1]: this is a _slight_ oversimplification; what the `--program` mode will actually unparse is anything that's contained in the definition's syntax module - so productions that are defined in the semantics module won't unparse properly.

**Comment by yanliu18** [comment]
> It _will_ do that @yanliu18, but only reliably for the contents of the K cell[1](#user-content-fn-1-de0eca5b9d54095adeb02cf7b042d87a) - if you wanted to unparse back to MIR using this mode, you could write a Pyk function to grab the K cell and pass the contents to the unparser.
> 
> ## Footnotes
> 1. this is a _slight_ oversimplification; what the `--program` mode will actually unparse is anything that's contained in the definition's syntax module - so productions that are defined in the semantics module won't unparse properly. [↩](#user-content-fnref-1-de0eca5b9d54095adeb02cf7b042d87a)

Thank you for the advice. I'll submit an issue to properly do the unparsing.
