### ISSUE TITLE
[K-Bug] Incorrect parsing and crash with ambiguous contextual function

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3880]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v6.0.137

### Operating System

Linux

### K Definitions (If Possible)

`test-exp1.k`
<pre>
module TEST-EXP1
imports INT
syntax Exp1 ::= foo() [function]
              | Exp1Val()

syntax Exp2 ::= foo() [function]
              | Exp1 

configuration &lt;k&gt; $PGM:Exp2 &lt;/k&gt;
              &lt;val&gt; Exp1Val():<b>Exp1</b> &lt;/val&gt;

rule [[ foo() => VAL ]]
     &lt;val&gt; VAL &lt;/val&gt;
endmodule
</pre>

`test-exp2.k`
<pre>
module TEST-EXP2
imports INT
syntax Exp1 ::= foo() [function]
              | Exp1Val()

syntax Exp2 ::= foo() [function]
              | Exp1 

configuration &lt;k&gt; $PGM:Exp2 &lt;/k&gt;
              &lt;val&gt; Exp1Val():<b>Exp2</b> &lt;/val&gt;

rule [[ foo() => VAL ]]
     &lt;val&gt; VAL &lt;/val&gt;
endmodule
</pre>

#### TEST-EXP1
`kompile test-exp1.k --main-module TEST-EXP1 --syntax-module TEST-EXP1`

Output:
```
```
Parsed:
```
rule #withConfig(`foo()_TEST-EXP1_Exp1`(.KList)=>#SemanticCastToExp1(VAL),`<val>`(#noDots(.KList),#SemanticCastToExp1(VAL),#noDots(.KList))) requires #token("true","Bool") ensures #token("true","Bool")
```
`krun -cPGM='foo()' --definition test-exp1-kompiled`

Output:
```
/home/sguest/work/k/k-distribution/target/release/k/bin/../lib/kframework/k-util.sh: line 114: 3983362 Segmentation fault      (core dumped) "$@"
[Error] krun: ./test-exp1-kompiled/interpreter 
/tmp/.krun-2023-12-15-12-33-40-Lcx1VQpGb6/tmp.in.M633PiUsc0 -1 
/tmp/.krun-2023-12-15-12-33-40-Lcx1VQpGb6/result.kore
[Error] krun: Backend crashed during rewriting with exit code 139
```

#### TEST-EXP2
`kompile test-exp2.k --main-module TEST-EXP2 --syntax-module TEST-EXP2`

Output:
```
SortGeneratedTopCell{}
inj{SortExp1{}, SortExp2{}}
java.util.NoSuchElementException: key not found: inj{SortExp1{}, SortExp2{}}
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:107)
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:105)
        at org.kframework.backend.llvm.matching.Fringe.injections(Matrix.scala:260)
        at org.kframework.backend.llvm.matching.Column.$anonfun$signatureForKey$2(Matrix.scala:120)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.kframework.backend.llvm.matching.Column.signatureForKey(Matrix.scala:120)
        at org.kframework.backend.llvm.matching.BHeuristic$.bf(Heuristics.scala:244)
        at org.kframework.backend.llvm.matching.BHeuristic$.computeScoreForKey(Heuristics.scala:253)
        at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey(Matrix.scala:40)
        at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey$(Matrix.scala:25)
        at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:52)
        at org.kframework.backend.llvm.matching.Column.zeroOrHeuristic$2(Matrix.scala:90)
        at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1(Matrix.scala:92)
        at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1$adapted(Matrix.scala:92)
        at scala.collection.immutable.List.map(List.scala:297)
        at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:92)
        at org.kframework.backend.llvm.matching.Column.computeScore(Matrix.scala:83)
        at org.kframework.backend.llvm.matching.Column.score$lzycompute(Matrix.scala:68)
        at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:68)
        at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:78)
        at org.kframework.backend.llvm.matching.MatrixColumn.score$lzycompute(Matrix.scala:49)
        at org.kframework.backend.llvm.matching.MatrixColumn.score(Matrix.scala:49)
        at org.kframework.backend.llvm.matching.Heuristic$.getBest(Heuristics.scala:81)
        at org.kframework.backend.llvm.matching.Matrix.bestColIx$lzycompute(Matrix.scala:566)
        at org.kframework.backend.llvm.matching.Matrix.bestColIx(Matrix.scala:561)
        at org.kframework.backend.llvm.matching.Matrix.compileInternal(Matrix.scala:883)
        at org.kframework.backend.llvm.matching.Matrix.compile(Matrix.scala:860)
        at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:40)
        at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
        at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:62)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:114)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:127)
        at org.kframework.main.Main.runApplication(Main.java:117)
        at org.kframework.main.Main.main(Main.java:58)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(NoSuchElementException: key not found: inj{SortExp1{}, SortExp2{}})
```
Parsed:
```
rule #withConfig(`foo()_TEST-EXP2_Exp1`(.KList)=>#SemanticCastToExp2(VAL),`<val>`(#noDots(.KList),#SemanticCastToExp2(VAL),#noDots(.KList))) requires #token("true","Bool") ensures #token("true","Bool")
```
`krun -cPGM='foo()' --definition test-exp2-kompiled`

Output:
```
/home/sguest/work/k/k-distribution/target/release/k/bin/../lib/kframework/k-util.sh: line 105: test-exp2-kompiled/interpreter: No such file or directory
[Error] krun: test-exp2-kompiled/interpreter 
/tmp/.krun-2023-12-15-12-39-11-cvYfJjUyQA/tmp.in.IsExgwJATj -1 
/tmp/.krun-2023-12-15-12-39-11-cvYfJjUyQA/result.kore
[Error] krun: Backend crashed during rewriting with exit code 127
```

### Expected Results

In both cases, there are multiple valid sort assignments, so we should report an ambiguity.

`test-exp1.k`
- `foo()::Exp1` and `VAL::Exp1`
- `foo()::Exp2` and `VAL::Exp1`

`test-exp2.k`
- `foo()::Exp1` and `VAL::Exp1`
- `foo()::Exp2` and `VAL::Exp2`

**Comment by Scott-Guest** [comment]
On a cursory glance, I think this is due to the fact that
- Type inference relies on there being no ambiguity in the LHS of a function rule 
- PushTopAmbiguities fails to handle contextual functions

**Comment by Scott-Guest** [comment]
On further inspection, this fails more egregiously even without the contextual aspect. In particular,
```
module TEST-EXP
imports INT
syntax Exp1 ::= foo() [function]
              | Exp1Val()

syntax Exp2 ::= foo() [function]
              | Exp1 

configuration <k> $PGM:Exp2 </k>

rule foo() => Exp1Val()
endmodule
```
does not report an ambiguity and always parses with foo()::Exp1. 

Even adding a strict cast
```
rule foo()::Exp2 => Exp1Val()
```
still parses as `Exp1` without any warnings or errors!

**Comment by Scott-Guest** [comment]
The remaining issues are related to type-inference, so blocked on the type-inference rewrite #3848
