### ISSUE TITLE
Sort with multiple syntatic list productions throws `AssertionError`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4079]
K version: `v6.3.26`

```k
// user-list.k
module USER-LIST
    imports BOOL-SYNTAX
    imports INT-SYNTAX

    syntax Foo ::= List{Bool, ","}
    syntax Foo ::= List{Int, ";"}
endmodule
```

```
$ kompile user-list.k --syntax-module USER-LIST --debug
java.lang.AssertionError
        at org.kframework.definition.UserList.getLists(UserList.java:49)
        at org.kframework.parser.inner.RuleGrammarGenerator.getCombinedGrammarImpl(RuleGrammarGenerator.java:735)
        at org.kframework.parser.inner.ParseInModule.getParsingModule(ParseInModule.java:183)
        at org.kframework.parser.inner.kernel.Scanner.<init>(Scanner.java:105)
        at org.kframework.parser.inner.ParseInModule.getScanner(ParseInModule.java:314)
        at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:560)
        at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:267)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:390)
        at org.kframework.kompile.Kompile.run(Kompile.java:213)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:91)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:60)
        at org.kframework.main.Main.runApplication(Main.java:127)
        at org.kframework.main.Main.runApplication(Main.java:117)
        at org.kframework.main.Main.main(Main.java:58)
[Error] Internal: Uncaught exception thrown of type AssertionError
(AssertionError: null)
```

**Comment by Baltoli** [comment]
We just want to throw an error when two syntactic list productions appear on the same sort; code can't be relying on this so we don't lose any existing behaviours by prohibiting it.
