### ISSUE TITLE
Special first character in main module name breaks kompilation

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4147]
Example:

```
module _TEST
endmodule
```

Error:

```
$ kompile _test.k --syntax-module _TEST --debug
com.runtimeverification.k.kore.parser.ParseError: ERROR: Line 65: Column 8: Expected <Identifier>, but '''
module 'Unds'TEST
       ^
        at com.runtimeverification.k.kore.parser.TextToKore.error(TextToKore.scala:851)
        at com.runtimeverification.k.kore.parser.TextToKore.error(TextToKore.scala:855)
        at com.runtimeverification.k.kore.parser.TextToKore.parseId(TextToKore.scala:774)
        at com.runtimeverification.k.kore.parser.TextToKore.parseModule(TextToKore.scala:180)
        at com.runtimeverification.k.kore.parser.TextToKore.parseModules(TextToKore.scala:193)
        at com.runtimeverification.k.kore.parser.TextToKore.parseDefinition(TextToKore.scala:155)
        at com.runtimeverification.k.kore.parser.TextToKore.parse(TextToKore.scala:91)
        at com.runtimeverification.k.kore.parser.TextToKore.parse(TextToKore.scala:64)
        at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:21)
        at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
        at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:68)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:114)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:60)
        at org.kframework.main.Main.runApplication(Main.java:127)
        at org.kframework.main.Main.runApplication(Main.java:117)
        at org.kframework.main.Main.main(Main.java:58)
[Error] Internal: Uncaught exception thrown of type ParseError (ParseError:
ERROR: Line 65: Column 8: Expected <Identifier>, but '''
module 'Unds'TEST
       ^)
```

## Analysis

The outer lexer allows a KAST module name to start with `#` or `_`:

https://github.com/runtimeverification/k/blob/1d6d0a802856eba785e9e62b0f8b10e4612a3f21/kernel/src/main/javacc/Outer.jj#L550

When converting to KORE, this character gets munged, hence the KORE module name will start with `'`, which is not a valid first character in KORE module names:

https://github.com/runtimeverification/haskell-backend/blob/27a47a7de65d79c40615d993e85a2e0c7c8ed343/docs/kore-syntax.md?plain=1#L119

Since `ModuleToKORE` flattens the definition, the error is not present for any other module than the main one.

## Potential fixes

1. `ModuleToKORE` could ensure correct translation by appending `Mod` or a similar prefix to the munged module name. However, this change could potentially cause issues in our tooling.
2. Restrict what first characters are allowed in module names. This could make some of the downstream semantics to not kompile, but the error message is clear and the fix is trivial.
3. Restrict what first characters are allowed in the module name. We would face this issue once again when making KORE kompilation modular (#3948).

**Comment by gtrepta** [comment]
We should check if any downstream semantics use a special first character for a module name. If none of them do, then I think restricting the first character would be a good solution.

**Comment by tothtamas28** [comment]
Let's restrict the first character to something that's not munged (upper or lower case letter in particular).
