### ISSUE TITLE
Pass regression-new test-suite

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#4194]
We're aiming for CLI "compatibility" between several of the kore K commands:

- `kompile ...` and `pyk kompile ...`
- `krun ...` and `pyk run ...`
- `kprove ...` and `pyk prove ...`
- `kast ...` and `pyk parse ...`

Past PRs have introduced this compatibility, and slowly introduced the `regression-new` test-suite to the pyk system:

- https://github.com/runtimeverification/pyk/pull/980
- https://github.com/runtimeverification/pyk/pull/973
- https://github.com/runtimeverification/pyk/pull/958

I'll open a PR with the tests that are passing removed from teh skipped lists introduce in runtimeverification/pyk#980, and following that we need to make a study of the CLI options/modes that we don't support in `pyk ...` variants, and decide if we want to port them or not. Some of them may not be interesting to carry over in the same way.

**Comment by ehildenb** [comment]
Here are the other flags that are not supported currently by the pyk CLI tools and are causing tests to fail:

- `kompile`:
  - `-E`
  - `--post-process`
  - `--profile-rule-parsing`
  - `--top-cell`
  - `--bison-stack-max-depth` 
  - `--bison-parser-library` 
  - `-Wno` 
- `kprove`:
  - `--branching-allowed 1` 
  - `--debugger` 
  - `--debug-script` 
  - `--md-selector` 
  - `--smt` 
- `krun`:
  - `-cFoo=1`
  - `--io off`
  - `--output`
  - `--parser`
  - `--profile`
  - `--search`

**Comment by Baltoli** [comment]
We probably want to drop the warning flags in favour of a Pyk-based implementation of the same features (`--verbose` `--debug`).

**Comment by ehildenb** [comment]
Another thing that I've not been updating is the negative tests, where they are expected to fail and we're comparing failure output. Python error system also takes a generally different approach to Java's, in the sense that we've been throwing exceptions and letting Python's stack trace bubble up with the exception. But we didn't implement custom error handling like how the Java codebase. It seems a common choice in Python to use the defaults, but maybe there are specific cases we want more handled/controlled errors? Not sure.

Either way, it seems like we need to agree on what the new output should look like.

**Comment by Baltoli** [comment]
> ... we're comparing failure output ...

Hopefully in the medium-long term we can make progress on porting away from the Makefile infrastructure in favour of Pytest, which will help reduce our reliance on textual comparisons.

**Comment by ehildenb** [comment]
An example of how output on failure can change:

```
diff --git a/regression-new/bad-bytes-literal/quote.k.out b/regression-new/bad-bytes-literal/quote.k.out
index 0044de48..7f09ab0d 100644
--- a/regression-new/bad-bytes-literal/quote.k.out
+++ b/regression-new/bad-bytes-literal/quote.k.out
@@ -1,6 +1,26 @@
 [Error] Inner Parser: Scanner error: unexpected character sequence '"'.
        Source(quote.k)
        Location(6,24,6,25)
        6 |         rule <k> b""" => b"" </k>
          .                            ^
 [Error] Compiler: Had 1 parsing errors.
+Traceback (most recent call last):
+  File "/home/dev/src/pyk/src/pyk/ktool/kompile.py", line 174, in __call__
+    proc_res = run_process(args, logger=_LOGGER, cwd=cwd, check=check)
+  File "/home/dev/src/pyk/src/pyk/utils.py", line 427, in run_process
+    res.check_returncode()
+  File "/usr/lib/python3.10/subprocess.py", line 457, in check_returncode
+    raise CalledProcessError(self.returncode, self.args, self.stdout,
+subprocess.CalledProcessError: Command '('kompile', 'quote.k', '--md-selector', 'k', '--emit-json', '--warnings', 'none', '--backend', 'llvm', '--output-definition', 'quote-kompiled', '--type-inference-mode', 'c>
+
+The above exception was the direct cause of the following exception:
+
+Traceback (most recent call last):
+  File "<string>", line 1, in <module>
+  File "/home/dev/src/pyk/src/pyk/__main__.py", line 90, in main
+    execute(options)
+  File "/home/dev/src/pyk/src/pyk/__main__.py", line 311, in exec_kompile
+    Kompile.from_dict(kompile_dict)(
+  File "/home/dev/src/pyk/src/pyk/ktool/kompile.py", line 176, in __call__
+    raise RuntimeError(
+RuntimeError: ('Command kompile exited with code 113 for: quote.k', '', None, 113)
```

Basically same output, but we get a stack trace and the lines aren't wrapped. Thoughts?

**Comment by ehildenb** [comment]
Another example of differing output, when bad CLI options are passed:

```
diff --git a/regression-new/bad-flags/extra-flags.out b/regression-new/bad-flags/extra-flags.out
index ab1ab0e2..491380ae 100644
--- a/regression-new/bad-flags/extra-flags.out
+++ b/regression-new/bad-flags/extra-flags.out
@@ -1 +1,4 @@
-[Error] Critical: Only one main parameter allowed but found several: "--badflag" and "--extra"
+usage: pyk [-h]
+           {print,rpc-print,rpc-kast,prove-legacy,kompile,run,prove,graph-imports,coverage,kore-to-json,json-to-kore}
+           ...
+pyk: error: unrecognized arguments: --badflag --extra ---output-definition test-kompiled
diff --git a/regression-new/bad-flags/no-flags.out b/regression-new/bad-flags/no-flags.out
index 56ac5fd7..cd439f06 100644
--- a/regression-new/bad-flags/no-flags.out
+++ b/regression-new/bad-flags/no-flags.out
@@ -1,2 +1,15 @@
-[Error] Critical: You have to provide exactly one main file in order to do
-outer parsing.
+usage: pyk kompile [-h] [--verbose] [--debug] [--warnings WARNINGS] [-w2e]
+                   [-I INCLUDES] [--main-module MAIN_MODULE]
+                   [--syntax-module SYNTAX_MODULE] [--md-selector MD_SELECTOR]
+                   [--output-definition DEFINITION_DIR] [--backend BACKEND]
+                   [--type-inference-mode TYPE_INFERENCE_MODE] [--emit-json]
+                   [-ccopt CCOPTS] [--no-llvm-kompile] [--with-llvm-library]
+                   [--enable-llvm-debug]
+                   [--llvm-kompile-type LLVM_KOMPILE_TYPE]
+                   [--llvm-kompile-output LLVM_KOMPILE_OUTPUT]
+                   [--read-only-kompiled-directory] [-O0] [-O1] [-O2] [-O3]
+                   [--enable-search] [--coverage] [--gen-bison-parser]
+                   [--gen-glr-bison-parser] [--bison-lists]
+                   [--llvm-proof-hint-instrumentation]
+                   main_file
+pyk kompile: error: the following arguments are required: main_file
```

**Comment by Baltoli** [comment]
> but we get a stack trace

I realise on taking a second look that this will make error output sensitive to changes _elsewhere_ in the code, unless we do something like the current regression test suite does to `sed` out location-sensitive information.

Maybe it makes sense to do something like what the current frontend does and swallow / re-report errors at the top level? If we want to see a stack trace then we can add a `--debug` flag. There might be an ergonomic way to install this top-level error handling only when we run in the context of a CLI tool; if some other application is using Pyk as a library then they can get the raw exceptions to handle themselves.

**Comment by ehildenb** [comment]
That makes sense to me! Thanks for teh suggestion.

**Comment by ehildenb** [comment]
Changes we'll make:

- On calls to `run_process`, we'll handle things more gracefully. Specifically, if a non-zero return code and `check` is turned on, we'll print the K command, then print out stdout/stderr, then `sys.exti(...)` with the same return code.
- Thread through option `--no-exc-wrap` to `kompile`.
- Update expected output.
