### ISSUE TITLE
krun AssertationError with java backend in nightly 023a4b6 prebuilt binary

### ISSUE THREAD

**Issue by KPJoshi** [runtimeverification/k#42]
1. Get Nightly build of K framework at commit 023a4b6 **Prebuilt K binary**
2. Open terminal and change into the directory containing the `kool-untyped.k` tutorial
3. Run `../../../../bin/kompile --backend java kool-untyped.k`
4. Run `../../../../bin/krun --debug tests/field.kool`

Issue does not occur with default backend.
I'm using Java 1.8.0_151 on Ubuntu 16.04

```
java.lang.AssertionError: unexpected class at matching: class org.kframework.backend.java.kil.KSequence
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:321)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAssoc(FastRuleMatcher.java:390)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:307)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.unifyEquality(FastRuleMatcher.java:173)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:375)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:331)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.addAndSimplify(ConjunctiveFormula.java:149)
	at org.kframework.backend.java.kil.ConstrainedTerm.lambda$evaluateConstraints$0(ConstrainedTerm.java:208)
	at org.kframework.backend.java.kil.ConstrainedTerm$$Lambda$248.000000009D2C5F20.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:204)
	at java.util.Iterator.forEachRemaining(Iterator.java:127)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1812)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:719)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:510)
	at org.kframework.backend.java.kil.ConstrainedTerm.evaluateConstraints(ConstrainedTerm.java:216)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchRulePattern(FastRuleMatcher.java:111)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:154)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:95)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:82)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:168)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
	at org.kframework.krun.KRun.run(KRun.java:99)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:90)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
java.lang.AssertionError: unexpected class at matching: class org.kframework.backend.java.kil.KSequence
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:321)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAssoc(FastRuleMatcher.java:390)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:307)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:299)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.unifyEquality(FastRuleMatcher.java:173)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:375)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:331)
	at org.kframework.backend.java.symbolic.ConjunctiveFormula.addAndSimplify(ConjunctiveFormula.java:149)
	at org.kframework.backend.java.kil.ConstrainedTerm.lambda$evaluateConstraints$0(ConstrainedTerm.java:208)
	at org.kframework.backend.java.kil.ConstrainedTerm$$Lambda$248.000000009D2C5F20.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:204)
	at java.util.Iterator.forEachRemaining(Iterator.java:127)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1812)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:719)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:510)
	at org.kframework.backend.java.kil.ConstrainedTerm.evaluateConstraints(ConstrainedTerm.java:216)
	at org.kframework.backend.java.symbolic.FastRuleMatcher.matchRulePattern(FastRuleMatcher.java:111)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:154)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:95)
	at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:82)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:168)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
	at org.kframework.krun.KRun.run(KRun.java:99)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:90)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (unexpected class
at matching: class org.kframework.backend.java.kil.KSequence)
```

**Comment by joshpoll** [comment]
Bump. It would be great if KOOL could work on the java backend, but this is still broken with the same error.

**Comment by ehildenb** [comment]
Because we are no longer actively developing the Java backend, I'm closing this. If you need concrete execution, you can use the LLVM backend on KOOL. If you need symbolic execution, give the Haskell backend a try insteaad.
