### ISSUE TITLE
Default configuration is not created in kprove

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#420]
Test:
def.k
```
module DEF
    imports INT

    syntax Term ::= "start"
                  | "end"

    rule start => end

/* Will make kprove work
    configuration <T>
      <k> $PGM:K </k>
    </T>
*/
endmodule
```

def-spec.k
```
require "def.k"
module DEF-SPEC
    imports DEF
    rule start => end
endmodule
```

Commands:
$ kompile --debug -v --backend java def.k
$ kprove def-spec.k -m DEF -v --debug

Result:
```
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:38)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:36)
        at scala.collection.MapLike$$anon$1.next(MapLike.scala:188)
        at scala.collection.IterableLike.head(IterableLike.scala:106)
        at scala.collection.IterableLike.head$(IterableLike.scala:105)
        at scala.collection.AbstractIterable.head(Iterable.scala:54)
        at org.kframework.compile.ConfigurationInfoFromModule.<init>(ConfigurationInfoFromModule.scala:73)
        at org.kframework.compile.AddImplicitComputationCell.transformModule(AddImplicitComputationCell.java:35)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at org.kframework.backend.java.symbolic.JavaBackend.lambda$specificationSteps$7(JavaBackend.java:124)
        at org.kframework.kprove.KProve.getProofDefinition(KProve.java:104)
        at org.kframework.kprove.KProve.run(KProve.java:57)
        at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:92)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:59)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:107)
        at org.kframework.main.Main.main(Main.java:53)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
```

**Comment by ehildenb** [comment]
@denis-bogdanas is this still an issue? If not, please close.

**Comment by ehildenb** [comment]
Closing as there is no response, feel free to re-open.
