### ISSUE TITLE
java.util.NoSuchElementException: None.get while parsing

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#423]
This error seems to happen as specs become kind of large. Here's a trace:
```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at org.kframework.parser.TreeNodesToKORE.termConsToKApply(TreeNodesToKORE.scala:42)
	at org.kframework.parser.TreeNodesToKORE.apply(TreeNodesToKORE.scala:22)
	at org.kframework.parser.TreeNodesToKORE.$anonfun$termConsToKApply$4(TreeNodesToKORE.scala:43)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.TreeNodesToKORE.termConsToKApply(TreeNodesToKORE.scala:43)
	at org.kframework.parser.TreeNodesToKORE.apply(TreeNodesToKORE.scala:22)
	at org.kframework.parser.TreeNodesToKORE.$anonfun$termConsToKApply$4(TreeNodesToKORE.scala:43)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.TreeNodesToKORE.termConsToKApply(TreeNodesToKORE.scala:43)
	at org.kframework.parser.TreeNodesToKORE.apply(TreeNodesToKORE.scala:22)
	at org.kframework.parser.TermCons.toString(treeNodes.scala:42)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.kframework.parser.concrete2kore.disambiguation.AmbFilter.apply(AmbFilter.java:66)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:106)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.GeneralTransformer.applyTerm(Transformer.scala:98)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:120)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:115)
	at org.kframework.parser.GeneralTransformer.apply(Transformer.scala:108)
	at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:224)
	at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:144)
	at org.kframework.kompile.DefinitionParsing.performParse(DefinitionParsing.java:399)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$15(DefinitionParsing.java:286)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:288)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$7(DefinitionParsing.java:258)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:73)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:110)
	at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:258)
	at org.kframework.kompile.DefinitionParsing.parseModules(DefinitionParsing.java:140)
	at org.kframework.kompile.Kompile.parseModules(Kompile.java:293)
	at org.kframework.kprove.KProve.getProofDefinition(KProve.java:99)
	at org.kframework.kprove.KProve.run(KProve.java:57)
	at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:58)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:107)
	at org.kframework.main.Main.main(Main.java:53)
```
while parsing https://gist.github.com/MrChico/7a1acdda5e92e966ac1f0421905fdcb0

**Comment by dwightguth** [comment]
While this stack trace tells me exactly what is going wrong, I can't quite figure out how the thing that is happening could be possible, and I can't investigate further because the example you gave me isn't self contained enough to reproduce. If you can give me a self contained example, I'll definitely investigate further, but right now I don't know how to figure out what is causing this, or what else to try to investigate.

**Comment by MrChico** [comment]
This example throws the error when run with the latest evm-semantics using:
`kprove --directory ~/evm-semantics/.build/java Dai_transferFrom-diff_fail.k`
https://github.com/MrChico/err

**Comment by dwightguth** [comment]
This was happening because an error was thrown while creating an error message for an ambiguity warning reported in your spec. I have a pull request in review now that fixes the crash, but you can also resolve the issue by fixing the ambiguity in your spec. Here is what kprove reports after the bug has been fixed:
```
[Error] Critical: Rule requires clause evaluates to false:
rule too long...
        Source: /home/dwightguth/err/Dai_transferFrom-diff_fail.k
Location(10,3,113,26)
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax Bool ::= Bool "orBool" Bool [boolOperation() function() functional()
hook(BOOL.or) latex({#1}\vee_{\scriptstyle\it Bool}{#2}) left() smt-hook(or)]

`_orBool__BOOL`(#rangeUInt(#token("256","Int"),`_-Int__INT-COMMON`(#SemanticCastToInt(#token("Allowed","#KVariable")),#SemanticCastToInt(#token("ABI_wad","#KVariable")))),`_andBool_`(`_orBool__BOOL`(`_==Int_`(#SemanticCastToInt(#token("ABI_src","#KVariable")),#SemanticCastToInt(#token("CALLER_ID","#KVariable"))),`_==Int_`(#SemanticCastToInt(#token("Allowed","#KVariable")),`maxUInt256_EVM-DATA`(.KList))),`_==Int_`(#SemanticCastToInt(#token("VCallValue","#KVariable")),#token("0","Int"))))
2: syntax Bool ::= Bool "andBool" Bool [boolOperation() function() functional()
hook(BOOL.and) klabel(_andBool_) latex({#1}\wedge_{\scriptstyle\it Bool}{#2})
left() smt-hook(and) symbol()]

`_andBool_`(`_orBool__BOOL`(#rangeUInt(#token("256","Int"),`_-Int__INT-COMMON`(#SemanticCastToInt(#token("Allowed","#KVariable")),#SemanticCastToInt(#token("ABI_wad","#KVariable")))),`_orBool__BOOL`(`_==Int_`(#SemanticCastToInt(#token("ABI_src","#KVariable")),#SemanticCastToInt(#token("CALLER_ID","#KVariable"))),`_==Int_`(#SemanticCastToInt(#token("Allowed","#KVariable")),`maxUInt256_EVM-DATA`(.KList)))),`_==Int_`(#SemanticCastToInt(#token("VCallValue","#KVariable")),#token("0","Int")))
        Source(/home/dwightguth/err/Dai_transferFrom-diff_fail.k)
        Location(109,14,110,33)
```

**Comment by MrChico** [comment]
Ah, that's a lot more helpful of an error message. I see the problem in the spec now, thanks!
