### ISSUE TITLE
Pyk KLLVM fixtures are unsound

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#4302]
When running the tests for Pyk's LLVM backend bindings, it's possible to see crashes if two tests share the same Pytest runner.

For example, I can reproduce this with:
```console
$ make test-integration TEST_ARGS='-n0 -k "test_simplify[literal] or test_steps_1" --log-cli-level=DEBUG'
```
which forces precisely two mutually incompatible test cases to run in sequence on the same runner. The logs produced are:
```
poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: pyk (7.0.0)
poetry run pytest src/tests/integration --maxfail=1 --verbose --durations=0 --numprocesses=4 --dist=worksteal -n0 -k "test_simplify[literal] or test_steps_1" --log-cli-level=DEBUG
================================================= test session starts ==================================================
platform darwin -- Python 3.12.3, pytest-8.1.1, pluggy-1.4.0 -- /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python
cachedir: .pytest_cache
rootdir: /Users/brucecollie/code/k/pyk
configfile: pyproject.toml
plugins: pyk-7.0.0, cov-5.0.0, xdist-3.5.0, timeout-2.3.1, mock-3.14.0
collecting ...
------------------------------------------------- live log collection --------------------------------------------------
INFO     pyk.kllvm.compiler:compiler.py:39 Compiling pythonast extension: _kllvm.cpython-312-darwin.so
INFO     pyk.kllvm.compiler:utils.py:433 Running: llvm-kompile pythonast --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/tmpjhgwpeco
INFO     pyk.kllvm.compiler:utils.py:448 Completed in 3.028s with status 0: llvm-kompile pythonast --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/tmpjhgwpeco
collected 824 items / 822 deselected / 2 selected

src/tests/integration/kllvm/test_simplify.py::TestSimplify::test_simplify[literal]
---------------------------------------------------- live log setup ----------------------------------------------------
INFO     pyk.ktool.kompile:utils.py:433 Running: kompile /Users/brucecollie/code/k/pyk/src/tests/integration/test-data/k-files/imp.k --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0 --type-inference-mode checked --warnings-to-errors
INFO     pyk.ktool.kompile:utils.py:448 Completed in 4.384s with status 0: kompile /Users/brucecollie/code/k/pyk/src/tests/integration/test-data/k-files/imp.k --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0 --type-inference-mode checked --warnings-to-errors
INFO     pyk.kllvm.compiler:compiler.py:89 Compiling python extension: _kllvm_runtime.cpython-312-darwin.so
INFO     pyk.kllvm.compiler:utils.py:433 Running: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0
INFO     pyk.kllvm.compiler:utils.py:448 Completed in 2.110s with status 0: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/imp-llvm-0
PASSED                                                                                                           [ 50%]
src/tests/integration/kllvm/test_step.py::TestStep::test_steps_1
---------------------------------------------------- live log setup ----------------------------------------------------
INFO     pyk.ktool.kompile:utils.py:433 Running: kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/k-files/definition-0.k --main-module STEPS --syntax-module STEPS --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1 --type-inference-mode checked --warnings-to-errors
INFO     pyk.ktool.kompile:utils.py:448 Completed in 3.988s with status 0: kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/k-files/definition-0.k --main-module STEPS --syntax-module STEPS --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1 --type-inference-mode checked --warnings-to-errors
INFO     pyk.kllvm.compiler:compiler.py:89 Compiling python extension: _kllvm_runtime.cpython-312-darwin.so
INFO     pyk.kllvm.compiler:utils.py:433 Running: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1
INFO     pyk.kllvm.compiler:utils.py:448 Completed in 2.023s with status 0: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1
FAILED                                                                                                           [100%]

======================================================= FAILURES =======================================================
________________________________________________ TestStep.test_steps_1 _________________________________________________

self = <integration.kllvm.test_step.TestStep object at 0x104f31cd0>
runtime = <pyk.kllvm.runtime.Runtime object at 0x104e5fb00>

    def test_steps_1(self, runtime: Runtime) -> None:
>       term = runtime.term(start_pattern())

src/tests/integration/kllvm/test_step.py:27:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pyk.kllvm.runtime.Runtime object at 0x104e5fb00>
pattern = LblinitGeneratedTopCell{}(Lbl'Unds'Map'Unds'{}(Lbl'Stop'Map{}(),Lbl'UndsPipe'-'-GT-Unds'{}(inj{SortKConfigVar{}, SortK... SortKItem{}}(inj{SortFoo{}, SortKItem{}}(Lblfoo'LParUndsRParUnds'STEPS'Unds'Foo'Unds'Int{}(\dv{SortInt{}}("100")))))))

    def term(self, pattern: Pattern) -> Term:
>       return Term(self._module.InternalTerm(pattern))
E       RuntimeError: No tag found for symbol inj{SortFoo{}, SortKItem{}}. Maybe attempted to evaluate a symbol with no rules?

src/pyk/kllvm/runtime.py:20: RuntimeError
-------------------------------------------------- Captured log setup --------------------------------------------------
INFO     pyk.ktool.kompile:utils.py:433 Running: kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/k-files/definition-0.k --main-module STEPS --syntax-module STEPS --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1 --type-inference-mode checked --warnings-to-errors
INFO     pyk.ktool.kompile:utils.py:448 Completed in 3.988s with status 0: kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/k-files/definition-0.k --main-module STEPS --syntax-module STEPS --emit-json --backend llvm --output-definition /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1 --type-inference-mode checked --warnings-to-errors
INFO     pyk.kllvm.compiler:compiler.py:89 Compiling python extension: _kllvm_runtime.cpython-312-darwin.so
INFO     pyk.kllvm.compiler:utils.py:433 Running: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1
INFO     pyk.kllvm.compiler:utils.py:448 Completed in 2.023s with status 0: llvm-kompile /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/definition.kore /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1/dt python --python /Users/brucecollie/Library/Caches/pypoetry/virtualenvs/pyk--TtZx6EN-py3.12/bin/python --python-output-dir /private/var/folders/8r/bzvz46gd0r5_fr11jt23fzyw0000gn/T/pytest-of-brucecollie/pytest-91/kompiled0/definition-0-llvm-1
================================================== slowest durations ===================================================
6.67s setup    src/tests/integration/kllvm/test_simplify.py::TestSimplify::test_simplify[literal]
6.18s setup    src/tests/integration/kllvm/test_step.py::TestStep::test_steps_1

(4 durations < 0.005s hidden.  Use -vv to show these durations.)
=============================================== short test summary info ================================================
FAILED src/tests/integration/kllvm/test_step.py::TestStep::test_steps_1 - RuntimeError: No tag found for symbol inj{SortFoo{}, SortKItem{}}. Maybe attempted to evaluate a symbol with no rules?
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 failed, 1 passed, 822 deselected in 16.32s =====================================
make: *** [test-integration] Error 1
```

I'm not sure exactly what the issue is here, but both tests will pass if run individually so I suspect it's something to do with their shared state. If you run with high parallelism you can run most of the KLLVM tests without seeing a failure; the following passes on my machine:
```console
$ make test-integration TEST_ARGS='-n14 -k kllvm'
```
while:
```console
$ make test-integration TEST_ARGS='-n4 -k kllvm'
```
fails stochastically with errors similar to the reproducible failure above.

**Comment by Baltoli** [comment]
@tothtamas28 and I looked at this and we suspect the issue may be that the Python module import subsystem is stateful; we should work out a better way of importing modules at runtime. It's not out of the question that we'd want to build multiple runtime modules and import them all into the same interpreter, for instance.

**Comment by Baltoli** [comment]
The problem is not in fact that the Python _module_ import system is stateful; it turns out to be down to a difference in how `dlopen` is handled on macOS vs. Linux. First, let's look at a reproducing example (`test.py`):
```python
from __future__ import annotations

import os
import sys
import tempfile
from typing import TYPE_CHECKING

from pyk.kllvm import load  # noqa: F401
from pyk.kllvm.compiler import compile_runtime
from pyk.kllvm.convert import pattern_to_llvm
from pyk.kllvm.importer import import_runtime
from pyk.kore.prelude import SORT_K_ITEM, inj, top_cell_initializer
from pyk.kore.syntax import App, SortApp
from pyk.ktool.kompile import kompile

if TYPE_CHECKING:
    from pathlib import Path

    from pyk.kllvm.ast import Pattern


def module(name: str) -> str:
    return f"""
        module {name.upper()}
            syntax {name.title()} ::= {name}() [symbol({name})]
                         | {name}Done()
            rule {name}() => {name}Done()
        endmodule
    """


def kompile_str(mod: str, main_mod: str) -> Path:
    with tempfile.NamedTemporaryFile() as tf:
        tf.write(mod.encode('utf-8'))
        tf.flush()

        return kompile(tf.name, output_dir=f'{main_mod.lower()}-kompiled', syntax_module=main_mod, main_module=main_mod)


def start_pattern(label: str, sort: str) -> Pattern:
    kore_sort = SortApp(f'Sort{sort}')
    term = inj(kore_sort, SORT_K_ITEM, App(f'Lbl{label}'))
    return pattern_to_llvm(top_cell_initializer({'$PGM': term})).desugar_associative()


if __name__ == '__main__':
    if 'local' in sys.argv:
        sys.setdlopenflags(os.RTLD_LOCAL)

    for mod in ['foo', 'bar']:
        if mod in sys.argv:
            out_dir = kompile_str(module(mod), mod.upper())
            compile_runtime(out_dir)
            runtime = import_runtime(out_dir)
            result = runtime.run(start_pattern(mod, mod.title()))
            print(result)
```

This code is pretty simple; it defines a handful of templates to handle writing out small K modules parameterised over a string, kompiling them, then running a program that takes a single rewrite step. At the command line, we can run:
```console
$ poetry run python3 test.py foo
Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortFoo{}, SortKItem{}}(LblfooDone'LParRParUnds'FOO'Unds'Foo{}()),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
```
which produces `fooDone()` as a result, as expected.

Similarly, we can run the equivalent program from the `bar` module:
```console
$ poetry run python3 test.py bar
Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortBar{}, SortKItem{}}(LblbarDone'LParRParUnds'BAR'Unds'Bar{}()),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
```
and get `barDone()` back.

The problem comes when we try to run both programs in sequence, reproducing the context from the test cases above:
```console
$ poetry run python3 test.py foo bar
Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortFoo{}, SortKItem{}}(LblfooDone'LParRParUnds'FOO'Unds'Foo{}()),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
Traceback (most recent call last):
  File "/Users/brucecollie/code/k/pyk/test.py", line 55, in <module>
    result = runtime.run(start_pattern(mod, mod.title()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brucecollie/code/k/pyk/src/pyk/kllvm/runtime.py", line 34, in run
    return self.step(pattern, depth=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brucecollie/code/k/pyk/src/pyk/kllvm/runtime.py", line 29, in step
    term = self.term(pattern)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/brucecollie/code/k/pyk/src/pyk/kllvm/runtime.py", line 20, in term
    return Term(self._module.InternalTerm(pattern))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No tag found for symbol inj{SortBar{}, SortKItem{}}. Maybe attempted to evaluate a symbol with no rules?
```

We can see that the `foo` program executes, but the `bar` one now crashes. On reproducing these steps on my Linux machine, however, no crash happens and everything is seemingly fine. Some [digging](https://developer.apple.com/forums/thread/670849) reveals that on macOS, the default behaviour of the dynamic linker is for the `RTLD_GLOBAL` flag to be set. This means that symbols in an extension module can be looked up globally by other modules loaded later on; by contrast, Linux sets `RTLD_LOCAL` as its default. Doing so means that symbols in a dynamically loaded module can only be referenced from within that module.

Without going too far into a diagnosis, I think basically what happens is that the dynamic loader finds the first module's definition of `get_tag_for_symbol_name` etc. when running programs with the second module's _Python runtime module_, causing the crash when it tries to look up a symbol that doesn't exist.

Running with `RTLD_LOCAL` on macOS confirms this theory:
```console
$ poetry run python3 test.py foo bar local
Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortFoo{}, SortKItem{}}(LblfooDone'LParRParUnds'FOO'Unds'Foo{}()),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortBar{}, SortKItem{}}(LblbarDone'LParRParUnds'BAR'Unds'Bar{}()),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0")))
```

My suggested fixes are:
- To fix the issue _now_, we should just force `RTLD_LOCAL` to be set when loading `_kllvm_runtime` modules. It's worth noting that we're doing something a little bit unusual with our use of extension modules; it's semantically valid (even expected) that Pyk might want to define a bunch of runtime modules and use them in isolation from each other, even though they all have overlapping sets of symbols defined.
- Longer term, to prevent regressions, we should merge the Nix flakes in the K repo and run Pyk integration tests on macOS explicitly.
