### ISSUE TITLE
UnsupportedOperationException with --search in OCaml backend

### ISSUE THREAD

**Issue by 15joeybloom** [runtimeverification/k#45]
1. Get Nightly build of K framework at commit 3af731f Prebuilt K binary
2. Open terminal and change into `tutorial/1_k/1_lambda/lesson_1`
3. Run `kompile --backend ocaml lambda.k`
4. Run `krun --search --debug tests/identity.lambda`

This occurs with Kool untyped as well. Running without `--search` is fine, though.
I'm running OCaml 4.03.1+dev0-2016-04-25 on Linux Mint 18.3.

```
java.lang.UnsupportedOperationException
	at org.kframework.backend.ocaml.OcamlRewriter$1.search(OcamlRewriter.java:116)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:55)
	at org.kframework.krun.KRun.run(KRun.java:99)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:90)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
java.lang.UnsupportedOperationException
	at org.kframework.backend.ocaml.OcamlRewriter$1.search(OcamlRewriter.java:116)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:55)
	at org.kframework.krun.KRun.run(KRun.java:99)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:90)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Internal: Uncaught exception thrown of type
UnsupportedOperationException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (null)
```

**Comment by suhabe** [comment]
I'm experiencing the same issue:
```
$ cd ~/k/k-distribution/tutorial/1_k/1_lambda/lesson_2

$ krun --version
RV-K version 1.0-SNAPSHOT
Git revision: 6bc147f
Git branch: master
Build date: Tue Jan 01 11:57:44 PST 2019

$ make clean
rm -rf ./lambda-kompiled

$ make
~/k/k-distribution/bin/kompile --syntax-module LAMBDA --backend java  lambda.k -d .
cat tests/free-variable-capture.lambda.in 2>/dev/null |~ /k/k-distribution/bin/krun tests/free-variable-capture.lambda --search --pattern "<k> V:K </k>"  -d . | diff - tests/free-variable-capture.lambda.out
java.lang.UnsupportedOperationException
	at org.kframework.backend.ocaml.OcamlRewriter$1.search(OcamlRewriter.java:116)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:55)
	at org.kframework.krun.KRun.run(KRun.java:87)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:159)
	at org.kframework.main.Main.nailMain(Main.java:75)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
0a1
> V ==K a ( ( lambda x . lambda y . x ) y z )
~/k/k-distribution/tutorial/1_k/1_lambda/lesson_1//../../../../include/ktest.mak:46: recipe for target 'tests/free-variable-capture.lambda' failed
make: *** [tests/free-variable-capture.lambda] Error 1
```

**Comment by suhabe** [comment]
I'm experiencing a similar issue:
```
$ cd ~/k/k-distribution/tutorial/1_k/1_lambda/lesson_2

$ krun --version
RV-K version 1.0-SNAPSHOT
Git revision: 6bc147f
Git branch: master
Build date: Tue Jan 01 11:57:44 PST 2019

$ make clean
rm -rf ./lambda-kompiled

$ make
~/k/k-distribution/bin/kompile --syntax-module LAMBDA --backend java  lambda.k -d .
cat tests/free-variable-capture.lambda.in 2>/dev/null |~ /k/k-distribution/bin/krun tests/free-variable-capture.lambda --search --pattern "<k> V:K </k>"  -d . | diff - tests/free-variable-capture.lambda.out
java.lang.UnsupportedOperationException
	at org.kframework.backend.ocaml.OcamlRewriter$1.search(OcamlRewriter.java:116)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:55)
	at org.kframework.krun.KRun.run(KRun.java:87)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:159)
	at org.kframework.main.Main.nailMain(Main.java:75)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
0a1
> V ==K a ( ( lambda x . lambda y . x ) y z )
~/k/k-distribution/tutorial/1_k/1_lambda/lesson_1//../../../../include/ktest.mak:46: recipe for target 'tests/free-variable-capture.lambda' failed
make: *** [tests/free-variable-capture.lambda] Error 1
```

**Comment by dwightguth** [comment]
Judging from your stack trace, it looks like a kserver is active, which probably means that you previously compiled this definition with the ocaml backend and the kserver cached the definition when you tried to run it. Then you switched to the java backend, but the kserver was never written to robustly invalidate caches when you recompile a definition, so it still thinks the definition has been built with the ocaml backend. If you run stop-kserver and then run these commands again, it should work. It might be slower though. Generally you should always stop and restart any kserver you started whenever you run kompile more than once on the same definition.

**Comment by dwightguth** [comment]
Note that the original error occurred because the ocaml backend does not support search.

**Comment by suhabe** [comment]
Running `stop-kserver` worked for me. Thank you!

**Comment by ehildenb** [comment]
Seems resolved. For the record, as @dwightguth says, `krun --search` is not supported by the ocaml backend (only by Java and Haskell backends), and the KServer causes issues with cacheing between kompile calls. This led to weird behavior when first running with ocaml backend then trying to switch to java backend for search.
