### ISSUE TITLE
[K-Bug] kgdb.py fails to print after single steps

### ISSUE THREAD

**Issue by pxhdev** [runtimeverification/k#4576]
### What component is the issue in?

llvm-backend

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v7.1.92 Build date:   Sat Aug 03 16:11:55 CST 2024

### Operating System

Linux

### K Definitions (If Possible)

```
module ASSIGNMENT-STRICT-SYNTAX
   imports INT-SYNTAX   // Int is the K built-in integer sort
   imports BOOL-SYNTAX  // Bool is the K built-in Boolean sort
   imports ID           // Id is the K built-in sort for identifiers (variables)

   // Expressions are either integer or Boolean expressions
   syntax Exp ::= IExp | BExp

   // An integer expression is either an integer value or a variable identifier
   syntax IExp ::= Int | Id 
   // or any of the arithmetic operators
   syntax IExp ::=  IExp "^" IExp [seqstrict]
                  | IExp "*" IExp [seqstrict]
                  | IExp "/" IExp [seqstrict]
                  > IExp "+" IExp [seqstrict]
                  | IExp "-" IExp [seqstrict]
   // or a bracketed integer expression
   syntax IExp ::= "(" IExp ")" [bracket]
                  
   // A Boolean expression is either a Boolean value
   syntax BExp ::= Bool
   // or any of the comparison operators
   syntax BExp ::=  IExp "<=" IExp [seqstrict]
                  | IExp "<"  IExp [seqstrict]
                  | IExp ">=" IExp [seqstrict]
                  | IExp ">"  IExp [seqstrict]
                  | IExp "==" IExp [seqstrict]
                  | IExp "!=" IExp [seqstrict]
   // or any of the  propositional connectives
   syntax BExp ::=  BExp "&&" BExp [seqstrict]
                  | BExp "||" BExp [seqstrict]
   // or a bracketed Boolean expression
   syntax BExp ::= "(" BExp ")" [bracket]

   // Signal when expression evaluation should stop
   syntax KResult ::= Int | Bool

   // A statement is
   syntax Stmt ::=  
      // either an assignment
      Id "=" IExp ";" [strict(2)]
      // or a (left-associative) sequence of statements 
      | Stmt Stmt     [left]
endmodule

module ASSIGNMENT-STRICT
   imports INT
   imports BOOL
   imports MAP
   imports ASSIGNMENT-STRICT-SYNTAX

   configuration
      // K cell, containing the statement to be executed
      <k> $PGM:Stmt </k>
      // Variable store, modelled as a K map, initially empty
      <store> .Map </store>

   // Expression evaluation
   
   // Base case: Variables evaluate to their values in the store
   rule 
     <k> I:Id => STORE[I] ... </k>
     <store> STORE </store>

   // Arithmetic operators 
   rule <k> I1 + I2 => I1 +Int I2 ... </k>
   rule <k> I1 - I2 => I1 -Int I2 ... </k>
   rule <k> I1 * I2 => I1 *Int I2 ... </k>
   rule <k> I1 / I2 => I1 /Int I2 ... </k>
   rule <k> I1 ^ I2 => I1 ^Int I2 ... </k>

   // Comparison operators
   rule <k> I1 <= I2 => I1  <=Int I2 ... </k>
   rule <k> I1  < I2 => I1   <Int I2 ... </k>
   rule <k> I1 >= I2 => I1  >=Int I2 ... </k>
   rule <k> I1  > I2 => I1   >Int I2 ... </k>
   rule <k> I1 == I2 => I1  ==Int I2 ... </k>
   rule <k> I1 != I2 => I1 =/=Int I2 ... </k>

   // Propositional connectives
   rule <k> B1 && B2 => B1 andBool B2 ... </k>
   rule <k> B1 || B2 => B1  orBool B2 ... </k>

   // Assignment
   rule 
      <k> ID = I:Int ; => .K ... </k>
      <store> STORE => STORE [ ID <- I ] </store>

   // Sequencing
   rule 
      <k> S1:Stmt S2:Stmt => S1 ~> S2 ... </k>

endmodule
```

### Steps to Reproduce

Compile and run with the following cmd:
```
kompile --verbose --backend llvm --enable-llvm-debug 04-assignment/assignment-strict.k
llvm-kompile /home/jah/experiments/zero-to-k-tutorial/assignment-strict-kompiled/definition.kore /home/jah/experiments/zero-to-k-tutorial/assignment-strict-kompiled/dt main -g -O1 -o
 /home/jah/experiments/zero-to-k-tutorial/assignment-strict-kompiled/interpreter -- -g
krun tests/04-assignment/2.assign --debugger #https://github.com/runtimeverification/zero-to-k-tutorial/blob/master/tests/04-assignment/2.assign
```
Step 3 times in GDB triggers the bug:
```
(gdb) k start
Temporary breakpoint 1 at 0x96b00
Starting program: /home/jah/experiments/zero-to-k-tutorial/assignment-strict-kompiled/interpreter /tmp/.krun-2024-08-07-00-14-05-Sqeq0eBctX/tmp.in.nicDb0ixQK -1 /tmp/.krun-2024-08-07-00-14-05-Sqeq0eBctX/result.kore
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/libthread_db.so.1".

Temporary breakpoint 1, 0x00005555555eab00 in main ()
0x00005555555c7580 in k_step (subject=<generatedTop>
  <k>
    x = 3 ; y = 4 ; z = x * y ; ~> .K
  </k>
  <store>
    .Map
  </store>
</generatedTop>)
(gdb) k step 3
Continuing.

Temporary breakpoint -7, 0x00005555555c7580 in k_step (subject=Traceback (most recent call last):
  File "<string>", line 392, in to_string
  File "<string>", line 623, in append
  File "<string>", line 615, in append
  File "<string>", line 510, in appendMap
  File "<string>", line 305, in __init__
gdb.error: No type named std::pair<KElem, KElem>.

Python Exception <class 'gdb.error'>: No type named std::pair<KElem, KElem>.
)
```

### Expected Results

Print the state correctly.

**Comment by gtrepta** [comment]
Thank you for reporting this. This is a bug and I've opened a PR to fix it.

**Comment by gtrepta** [comment]
@pxhdev Please try this with K v7.1.100 and let us know if your problem is fixed.

**Comment by pxhdev** [comment]
> @pxhdev Please try this with K v7.1.100 and let us know if your problem is fixed.

It works now. Thanks!
