### ISSUE TITLE
[Error] Critical: (null) while evaluating function _-Int_ * 43778

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#611]
Started having kprove throw this error after upgrading evm-semantics from https://github.com/kframework/evm-semantics/commit/087db3b548adb40c9000b24a65ca419c8ff18223 to current master on some proofs that were previously succeeding without issues.

Here's the full error message. https://dapp.ci/k-dss/4a62cfaf9bcd6718b2aa1dc383388458eddfa67d8953813f6ea4ba86f693cfd7.err.log

It seems to happen when trying to a trusted spec rule in a proof, for example in a spec like this: https://dapp.ci/k-dss/613759102a6e9b4e48d352ae377943b3c59ee05260f1b9114b42436db3cf797d.k at the point where the second rule matches and about to be applied

**Comment by MrChico** [comment]
Was able to generate a stack trace:
```
org.kframework.utils.errorsystem.KEMException: [Error] Critical:  (null)
  while evaluating function _-Int_ * 53606
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:110)
	at org.kframework.utils.errorsystem.KEMException.criticalError(KEMException.java:39)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:585)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
	at org.kframework.backend.java.util.RewriteEngineUtils.construct(RewriteEngineUtils.java:292)
	at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:535)
	at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:371)
	at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:305)
...
```

**Comment by MrChico** [comment]
I think I wrote lemmas that were leading to an infinite regress. I still think the error message could have been a little more helpful, but my issue is resolved and you are welcome to close this issue if you like

**Comment by ehildenb** [comment]
Closing as K has changed significantly, and we are targeting the Haskell backend now. Feel free to re-open if it's still an issue.
