### ISSUE TITLE
kompile fails with simple lambda.k example

### ISSUE THREAD

**Issue by Jake-Gillberg** [runtimeverification/k#81]
Compiled https://github.com/kframework/k5/commit/6e240f339ad719284d570289e7da36a03a3b9234 on debian stretch:

Trying to `kompile` a simple lambda definition gives an error.

lambda.k
```
module LAMBDA
  imports DOMAINS

  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
endmodule
```

`kompile -v --debug lambda.k` gives:

```
Parse command line options                                   =    41
Importing: Source(/home/dev/Lambda/./lambda.k)
Importing: Source(/home/dev/k5/k-distribution/target/release/k/include/builtin/prelude.k)
Importing: Source(/home/dev/k5/k-distribution/target/release/k/include/builtin/kast.k)
Importing: Source(/home/dev/k5/k-distribution/target/release/k/include/builtin/domains.k)
Importing: Source(/home/dev/Lambda/./lambda.k)
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:117)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:168)
	at org.kframework.kompile.DefinitionParsing.resolveConfigBubbles(DefinitionParsing.java:225)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:158)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:123)
	at org.kframework.kompile.Kompile.run(Kompile.java:107)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Compiler: Had 1 parsing errors.
[Error] Internal: gcc returned nonzero exit code. See output for details.
[Warning] Compiler: Could not find main syntax module with name LAMBDA-SYNTAX
in definition.  Use --syntax-module to specify one. Using LAMBDA as default.
```

**Comment by Jake-Gillberg** [comment]
I needed the flex runtime library, which was in a different package than `flex`. Installing `libfl-dev` did the trick.
