### ISSUE TITLE
Configurations definitions with empty `<k>` cell produce cryptic error messages

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#826]
Kompiling:

```
module TEST                                                                                    
    configuration <k> .K </k>                                                                       
endmodule                                                                                           
```

produces:

```
$ sp; "ext/k/k-distribution/target/release/k/bin/kompile" --backend "haskell" -I .build/defn/automaton  --directory ".build/defn/automaton" .build/automaton.k --debug







java.lang.IndexOutOfBoundsException: 0
	at scala.collection.LinearSeqOptimized.apply(LinearSeqOptimized.scala:63)
	at scala.collection.LinearSeqOptimized.apply$(LinearSeqOptimized.scala:61)
	at scala.collection.immutable.List.apply(List.scala:86)
	at scala.collection.convert.Wrappers$SeqWrapper.get(Wrappers.scala:63)
	at org.kframework.compile.AddCoolLikeAtt$1.apply(AddCoolLikeAtt.java:58)
	at org.kframework.compile.AddCoolLikeAtt$1.apply(AddCoolLikeAtt.java:47)
	at org.kframework.kore.KTransformer.apply(transformers.scala:11)
	at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
	at org.kframework.kore.FoldK.apply(transformers.scala:38)
	at org.kframework.kore.FoldK.apply(transformers.scala:47)
	at org.kframework.kore.KTransformer.apply(transformers.scala:12)
	at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
	at org.kframework.kore.FoldK.apply(transformers.scala:38)
	at org.kframework.compile.AddCoolLikeAtt.transform(AddCoolLikeAtt.java:70)
	at org.kframework.compile.AddCoolLikeAtt.add(AddCoolLikeAtt.java:29)
	at org.kframework.compile.AddCoolLikeAtt.add(AddCoolLikeAtt.java:78)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$1(transformers.scala:16)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$3(transformers.scala:22)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.mutable.AbstractSet.map(Set.scala:46)
	at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$2(transformers.scala:20)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:76)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:110)
	at org.kframework.backend.kore.KoreBackend.lambda$steps$2(KoreBackend.java:133)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at org.kframework.backend.kore.KoreBackend.lambda$steps$15(KoreBackend.java:172)
	at org.kframework.kompile.Kompile.run(Kompile.java:126)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:59)
	at org.kframework.main.Main.runApplication(Main.java:119)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:54)
[Error] Internal: Uncaught exception thrown of type IndexOutOfBoundsException
(0)
```

**Comment by nishantjr** [comment]
Ah, actually looks like it is not the absence of $PGM, but the empty K cell that causes the problem
