### ISSUE TITLE
scala.MatchError: Some(BAG.Bag) when compiling

### ISSUE THREAD

**Issue by stahlbauer** [runtimeverification/k#879]
I get the following error (stack trace):

```
scala.MatchError: Some(BAG.Bag) (of class scala.Some)
	at org.kframework.backend.llvm.matching.pattern.SortCategory$.apply(SortCategory.scala:22)
	at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:92)
	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$10(Generator.scala:99)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Generator$.genPatterns(Generator.scala:99)
	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genClauseMatrix$11(Generator.scala:134)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.backend.llvm.matching.Generator$.genClauseMatrix(Generator.scala:134)
	at org.kframework.backend.llvm.matching.Generator$.mkDecisionTree(Generator.scala:140)
	at org.kframework.backend.llvm.matching.Matching$.$anonfun$writeDecisionTreeToFile$4(Matching.scala:33)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:29)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:46)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:119)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:54)
[Error] Internal: Uncaught exception thrown of type MatchError (Some(BAG.Bag)
(of class scala.Some))
```

for the following K file:

```
module TEST
    
    imports DOMAINS

    syntax KResult ::= Int | Float | Bool | String

    configuration <T>
        <actors>
            <actor multiplicity="*">
                <threads>
                    <thread multiplicity="*">
                        <k> $PGM </k>
                        <stack> .List </stack>
                    </thread>
                </threads>
                <mem> .Map </mem>
            </actor>
        </actors>
    </T>

endmodule
```
by running the following command: `kompile --debug --backend llvm test.k`

I am using version: 
```
RV-K version 1.0-SNAPSHOT
Git revision: 7bdcf8f
Git branch: master
Build date: Tue Nov 05 09:00:46 CET 2019
```

Thank you :)

**Comment by dwightguth** [comment]
I would recommend adding `type="Set"` to the `actor` and `thread` cells.

**Comment by stahlbauer** [comment]
What is the difference to `type="Map"`? Would `<mem> .Map </mem>` be equivalent to `<mem type="Map"></map>`?

**Comment by dwightguth** [comment]
the `type` attribute applies only to cells with `multiplicity="*"` and tells K what type of collection you want to use internally to represent the collection of cells.

**Comment by stahlbauer** [comment]
That is, I would you `List` because an explicit ordering is required and uniqueness of elements is not intended?
