### ISSUE TITLE
Claims with the same definition but different attributes

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#900]
In a specification module, two claims with the same body, for example `rule a => b [one-path]` and `rule a => b [all-path]`, are translated to a single `kore` claim in `spec.kore`. These should be translated to different `kore` claims.

This has been tested on https://github.com/kframework/k/commit/96b27d3c9a20fe9c0da982470d0f89ca70aee1fc

**Comment by ehildenb** [comment]
@ana-pantilie if you have time, could you re-test this on latest K master and provide a minimal example?

**Comment by ana-pantilie** [comment]
@ehildenb For some reason after checking out `master`, updating the submodules and building with `mvn package` as I usually do, `kompile` throws the following exception:

```
java.lang.IncompatibleClassChangeError: Expecting non-static method 'com.beust.jcommander.internal.Console com.beust.jcommander.JCommander.getConsole()'
        at org.kframework.utils.inject.JCommanderModule.usage(JCommanderModule.java:54)
        at org.kframework.utils.inject.JCommanderModule.usage(JCommanderModule.java:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:250)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at org.kframework.main.Main.runApplication(Main.java:119)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.main.Main.main(Main.java:57)
[Error] Internal: Uncaught exception thrown of type
IncompatibleClassChangeError (IncompatibleClassChangeError: Expecting
non-static method 'com.beust.jcommander.internal.Console
com.beust.jcommander.JCommander.getConsole()')
```

**Comment by dwightguth** [comment]
Please run `mvn clean`.

**Comment by ana-pantilie** [comment]
`mvn clean` worked, so I was able to retest this and it's fixed now. Thanks!
