### ISSUE TITLE
Multiple kompile and krun failures on this example

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#946]
Version K-master, backend LLVM, Ubuntu19.10
```
module TEST
  imports INT
  imports MAP

  syntax Int ::= "start"
  configuration <k> start </k>
                <env> 1 |-> ListItem(2) ListItem(3) ListItem(4)
                      5 |-> ListItem(6) ListItem(7)
                      8 |-> ListItem(9) </env>

//  rule <k> start => E1 </k>
//       <env> 1 |-> E1 LRest:List ...</env>
endmodule
```
This exact example fails with:
```
radu@ubuntu:~/work/test$ kompile -ccopt -g test.k --debug
/usr/bin/opt-9: tmp.csc9oVqURj:1029:9: error: stored value and pointer type do not match
  store %block* %3, %mpz** %4
        ^
org.kframework.utils.errorsystem.KEMException: [Error] Critical: llvm-kompile returned nonzero exit code: 1
```
Change the sort of `start` to `KItem` and it kompiles, but krun fails with:
```
radu@ubuntu:~/work/test$ krun --debug
java.lang.IndexOutOfBoundsException: 0
	at scala.collection.LinearSeqOptimized.apply(LinearSeqOptimized.scala:63)
	at scala.collection.LinearSeqOptimized.apply$(LinearSeqOptimized.scala:61)
	at scala.collection.immutable.List.apply(List.scala:86)
	at org.kframework.definition.Production.nonterminal(outer.scala:481)
	at org.kframework.compile.AddSortInjections.visitChildren(AddSortInjections.java:202)
	at org.kframework.compile.AddSortInjections.internalAddSortInjections(AddSortInjections.java:128)
	at org.kframework.compile.AddSortInjections.addSortInjections(AddSortInjections.java:89)
	at org.kframework.compile.AddSortInjections.addInjections(AddSortInjections.java:83)
	at org.kframework.backend.llvm.LLVMRewriter$1.execute(LLVMRewriter.java:80)
	at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:69)
	at org.kframework.krun.KRun.run(KRun.java:87)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:95)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
```
Uncomment the rule, and get a different error message:
```
radu@ubuntu:~/work/test$ kompile -ccopt -g test.k --debug
java.util.NoSuchElementException: key not found: VarE1
        .........
	at org.kframework.backend.llvm.matching.Matrix.$anonfun$getLeaf$10(Matrix.scala:553)
        .........
```

Make `start` a function and force the match on only the first element of the list, and it kompiles:
```
module TEST
  imports INT
  imports MAP

  syntax Int ::= "start" [function]
  configuration <k> start </k>
                <env> 1 |-> ListItem(2) ListItem(3) ListItem(4)
                      5 |-> ListItem(6) ListItem(7)
                      8 |-> ListItem(9) </env>

  rule [[ start => E1 ]]
       <env> 1 |-> ListItem(E1) LRest:List ...</env>
endmodule
```
but krun still fails:
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000155554bc0899 in __GI_abort () at abort.c:79
#2  0x000000000028d696 in getTagForSymbolName ()
#3  0x0000000000299541 in allocatePatternAsConfiguration (Pattern=0x155554623330)
    at /home/radu/work/k/llvm-backend/src/main/native/llvm-backend/runtime/configurationparser/ConfigurationParser.cpp:34
#4  0x0000000000299629 in allocatePatternAsConfiguration (Pattern=0x155554623300)
    at /home/radu/work/k/llvm-backend/src/main/native/llvm-backend/runtime/configurationparser/ConfigurationParser.cpp:39
#5  0x00000000002990eb in parseConfiguration (filename=0x7fffffffe097 "/home/radu/work/test/./.krun-2019-12-04-15-22-19-125-f694dd1f-5dc4-476e-9c90-60a2cf90aab2/pgm.kore")
    at /home/radu/work/k/llvm-backend/src/main/native/llvm-backend/runtime/configurationparser/ConfigurationParser.cpp:88
#6  0x0000000000298f47 in main ()
```

**Comment by dwightguth** [comment]
In order:

1. This should be a kompile error because you have declared a new constructor of sort Int, which is a sort hooked to the integers.
2. This is a bug. I have created a PR that will fix it.
3. This should be a kompile error because you are trying to do associative matching on a List, which is not supported by K.
4. This should be a kompile error because your configuration declaration references a function which requires the entire configuration to evaluate, yet obviously the entire configuration does not exist yet while it is still being created. You cannot use the [[ ]] syntax within functions that are referenced by the initial configuration.

The kompile errors are being tracked in #239 , and the bug is fixed in #949 . I don't currently have the resources to implement all the frontend error checking that needs to be done, but thanks for bringing this to our attention so we can track it!
