### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (Either.right.get on Left)

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#959]
Ran into this monster while doing `kprove` on some deposit contract specs. Can't really minimize the example at this time, but here's a full stack trace in case there's an easy fix
```
java.util.NoSuchElementException: Either.right.get on Left
	at scala.util.Either$RightProjection.get(Either.scala:641)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:230)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:217)
	at org.kframework.parser.SafeTransformer.applyTerm(Transformer.scala:204)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:231)
	at org.kframework.parser.concrete2kore.disambiguation.PushTopAmbiguityUp.apply(PushTopAmbiguityUp.java:29)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:226)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:219)
	at org.kframework.parser.SafeTransformer.applyTerm(Transformer.scala:204)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:231)
	at org.kframework.parser.concrete2kore.disambiguation.PushTopAmbiguityUp.apply(PushTopAmbiguityUp.java:29)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:226)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:219)
	at org.kframework.parser.SafeTransformer.applyTerm(Transformer.scala:204)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:231)
	at org.kframework.parser.concrete2kore.disambiguation.PushTopAmbiguityUp.apply(PushTopAmbiguityUp.java:29)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:226)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:219)
	at org.kframework.parser.SafeTransformer.applyTerm(Transformer.scala:204)
	at org.kframework.parser.ChildrenMapping.$anonfun$mapChildrenStrict$1(Transformer.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.parser.ChildrenMapping.mapChildrenStrict(Transformer.scala:28)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:231)
	at org.kframework.parser.concrete2kore.disambiguation.PushTopAmbiguityUp.apply(PushTopAmbiguityUp.java:29)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:226)
	at org.kframework.parser.SafeTransformer.apply(Transformer.scala:219)
	at org.kframework.parser.concrete2kore.ParseInModule.disambiguateForUnparse(ParseInModule.java:291)
	at org.kframework.unparser.KPrint.unparseInternal(KPrint.java:194)
	at org.kframework.unparser.KPrint.unparseTerm(KPrint.java:188)
	at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:141)
	at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:119)
	at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:115)
	at org.kframework.backend.java.util.PrettyPrinter.prettyPrintBytes(PrettyPrinter.java:35)
	at org.kframework.backend.java.util.StateLog.writeNode(StateLog.java:145)
	at org.kframework.backend.java.util.StateLog.log(StateLog.java:108)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.lambda$prove$1(InitializeRewriter.java:251)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.prove(InitializeRewriter.java:256)
	at org.kframework.kprove.KProve.run(KProve.java:60)
	at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:90)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (Either.right.get on Left)
```

**Comment by dwightguth** [comment]
Unfortunately I really need to be able to reproduce this in order to debug further. I can tell roughly speaking what has gone wrong from the stack trace, but I can't figure out why it would happen, so I need to be able to investigate further. If you can provide me with a way to reproduce the issue, I will fix it.

**Comment by ehildenb** [comment]
This targets the Java backend, so I'm closing for now.

If you have reproduction steps, please re-open a new bug report with those steps.
