### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type IndexOutOfBoundsException.

### ISSUE THREAD

**Issue by prpr2770** [runtimeverification/k#962]
Running command: kompile imp.k --debug
java.lang.IndexOutOfBoundsException: 1
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14$$anonfun$apply$2.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14$$anonfun$apply$2.apply(MergeRules.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14.apply(MergeRules.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules.apply(MergeRules.scala:40)
	at org.kframework.kore.compile.MergeRules.apply(MergeRules.scala:15)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:73)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:114)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:111)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.java.symbolic.JavaBackend.lambda$steps$164(JavaBackend.java:99)
	at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$8/20224131.apply(Unknown Source)
	at org.kframework.kompile.Kompile.run(Kompile.java:120)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:110)
	at org.kframework.main.Main.runApplication(Main.java:100)
	at org.kframework.main.Main.main(Main.java:52)
java.lang.IndexOutOfBoundsException: 1
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14$$anonfun$apply$2.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14$$anonfun$apply$2.apply(MergeRules.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$14.apply(MergeRules.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:92)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8$$anonfun$15.apply(MergeRules.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:93)
	at org.kframework.kore.compile.MergeRules$$anonfun$8.apply(MergeRules.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.kore.compile.MergeRules.pushDisjunction(MergeRules.scala:77)
	at org.kframework.kore.compile.MergeRules.apply(MergeRules.scala:40)
	at org.kframework.kore.compile.MergeRules.apply(MergeRules.scala:15)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:73)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:114)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:111)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.kframework.backend.java.symbolic.JavaBackend.lambda$steps$164(JavaBackend.java:99)
	at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$8/20224131.apply(Unknown Source)
	at org.kframework.kompile.Kompile.run(Kompile.java:120)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:110)
	at org.kframework.main.Main.runApplication(Main.java:100)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type IndexOutOfBoundsException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KBott ::= KLabel "(" KList ")"
[Location(#token("29",Int),#token("20",Int),#token("29",Int),#token("108",Int))
Source(#token("/srv/www/k/imgs/releases/k/lib/java/../../include/builtin/kast.k",KString))
hook(#token("org.kframework.kore.KApply",AttributeValue))
klabel(#token("#KApply",AttributeValue)) klabel(#token("#KApply",KString))]
   
#KApply(#token(KLabel,"print"),#KList(#token(#KVariable,"P"),#token(#KVariable,"Ps")))
2: syntax Stmt ::= "print(" Ids ")"
[Location(#token("26",Int),#token("20",Int),#token("26",Int),#token("59",Int))
Source(#token("/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k",KString))
klabel(#token("print",AttributeValue)) klabel(#token("print",KString))]
    print(_,_(#token(#KVariable,"P"),#token(#KVariable,"Ps")))
	Source(/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k)
	Location(90,10,90,24)
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KBott ::= KLabel "(" KList ")"
[Location(#token("29",Int),#token("20",Int),#token("29",Int),#token("108",Int))
Source(#token("/srv/www/k/imgs/releases/k/lib/java/../../include/builtin/kast.k",KString))
hook(#token("org.kframework.kore.KApply",AttributeValue))
klabel(#token("#KApply",AttributeValue)) klabel(#token("#KApply",KString))]
    #KApply(#token(KLabel,"print"),#token(#KVariable,"Ps"))
2: syntax Stmt ::= "print(" Ids ")"
[Location(#token("26",Int),#token("20",Int),#token("26",Int),#token("59",Int))
Source(#token("/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k",KString))
klabel(#token("print",AttributeValue)) klabel(#token("print",KString))]
    print(#token(#KVariable,"Ps"))
	Source(/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k)
	Location(90,28,90,39)
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KBott ::= KLabel "(" KList ")"
[Location(#token("29",Int),#token("20",Int),#token("29",Int),#token("108",Int))
Source(#token("/srv/www/k/imgs/releases/k/lib/java/../../include/builtin/kast.k",KString))
hook(#token("org.kframework.kore.KApply",AttributeValue))
klabel(#token("#KApply",AttributeValue)) klabel(#token("#KApply",KString))]
    #KApply(#token(KLabel,"print"),.List{"_,_"}())
2: syntax Stmt ::= "print(" Ids ")"
[Location(#token("26",Int),#token("20",Int),#token("26",Int),#token("59",Int))
Source(#token("/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k",KString))
klabel(#token("print",AttributeValue)) klabel(#token("print",KString))]
    print(.List{"_,_"}())
	Source(/srv/kweb/kfiles/anon/9aad8f54-34cc-4834-9acc-bedeceff9c13/tutorial/ECEN5139/IMP4/./imp.k)
	Location(94,10,94,23)
----- End of process output.

**Comment by prpr2770** [comment]
The IMP.K code DOES NOT Correspond to the "IMP language" defined in the tutorrials. It's just named that way. The programing language I'm trying to implement is something different.

**Comment by ehildenb** [comment]
You'll need to post the input `imp.k` for us to reproduce/help.

**Comment by prpr2770** [comment]
The IMP.K file is as follows: 

requires "../KAT/kat.k"


module IMP-SYNTAX
  imports KAT
  syntax Exp  ::=  Id | Kat
                 | Exp "*"               [left, strict(1)]
                 > Exp ";" Exp          [left, strict]
                 | Exp "|" Exp          [left, strict]
                 | Exp "!=" Exp           [strict, latex({#1}\eq{#2})]
                 | Exp "==" Exp           [strict, latex({#1}\eq{#2})]
                 | "!" Exp                [strict]
                 > Exp "and" Exp          [left, strict]
                 | Exp "or" Exp           [left, strict]
                 | "(" Exp ")"            [bracket]
                // the below ones are doubtful

  syntax Block ::= "{" "}"
                 | "{" Stmt "}"

  syntax Stmt  ::= Block
                 | Id "=" Exp             [strict(2)]
                 | "print(" Ids ")"         [klabel(print)]
                 > Stmt Stmt                  [left] // [left, klabel(seqStmt)] //


  syntax Pgm ::= "kat" Ids ";" Stmt  [klabel(Pgm)]

  syntax Ids ::= List{Id,","} //[klabel(Ids)]

endmodule


module IMP
  imports IMP-SYNTAX

  syntax KResult ::= Kat


  configuration <T color="yellow">
                  <k color="green"> $PGM:Pgm </k>
                  <state color="red"> .Map </state>
                  <out> .List </out>
                </T>



  rule <k> X:Exp => I ...</k> <state>... X |-> I ...</state>
  rule <k> X = I:Exp => . ...</k> <state>... X |-> (_ => I) ...</state>

  rule ! B1:Kat => notKat B1
  rule B1:Kat * => B1 Kat*
  rule B1:Kat == B2:Kat => B1 ==Kat B2
  rule B1:Kat != B2:Kat => notKat(B1 ==Kat B2)
  rule B1:Kat ; B2:Kat => B1 Kat; B2
  rule B1:Kat | B2:Kat => B1 Kat| B2
  rule B1:Kat and B2:Kat => B1 andKat B2
  rule B1:Kat or B2:Kat => B1 orKat B2


  rule {} => .   [structural]
  rule {S} => S  [structural]

  rule S1:Stmt S2:Stmt => S1 ~> S2  [structural]
  

rule <k> kat (X,Xs => Xs);_ </k>
	<state> Rho:Map (.Map => X|-> ZERO) </state>
    requires notBool (X in keys(Rho))
rule kat .Ids; S => S  [structural] 

// ------------------------------------------------------
// Print:

rule <k> print( P, Ps ) => print( Ps ) ...</k> <out> . => ListItem(P) ...</out>
rule <k> print( .Ids ) => . ...</k>


endmodule

**Comment by ehildenb** [comment]
You'll have to supply `kat.k`. Basically you should supply everything we need to reproduce the error. Is it from https://github.com/kframework/kat?

**Comment by prpr2770** [comment]
The IMP.K file can be accessed [here](https://gist.github.com/prpr2770/e6fbb9d08062c0c9ea18d242b5d85fdf).

The KAT.K file can be accessed [here](https://gist.github.com/prpr2770/a55587a5f3e1486d613520040dc18832) 

The kat.k is NOT from /kframework/kat/ !

**Comment by prpr2770** [comment]
Thank you for your help with this issue. Kindly inform if I need to share my scripts in any other format.

**Comment by prpr2770** [comment]
@ehildenb May I have an estimate for how long it might take to get this issue resolved? Thanks!

**Comment by dwightguth** [comment]
Honestly this particular error is in a part of the code nobody on the project really understands anymore, and is moreover on a deprecated component that we are trying to migrate away from. So it's unlikely that this particular issue will be fixed. It's possible however that it  could be happening due to some flaw in the semantics that K isn't yet able to report a better error message for; I haven't looked at the example in detail. However, I notice you have some parsing ambiguities and are not using the latest version of K. I would recommend updating to the latest version of K and fixing the parsing ambiguities and seeing whether your issue remains after doing so. If it does, you might consider trying to move to either the llvm or haskell backends, depending on whether you are trying to perform concrete or symbolic execution.

**Comment by prpr2770** [comment]
@dwightguth I'm running the K-version that's being implemented on this website: http://www.kframework.org/tool/run/
Is that an outdated version of K? Is there any online implementation of K, that's upto date? Is there a VM or a docker-image that I can download, which contains the most-upto-date version of K?

**Comment by ehildenb** [comment]
@prpr2770 KWeb (the tool you linked) is a very outdated version of K I'm pretty sure. Can you build from source and run on your machine instead.

We don't have any intention of providing support for older versions of K, and we aren't directly in control of the KWeb tooling.

**Comment by prpr2770** [comment]
@ehildenb Thank you for the update. I shall try to build from source and run my scripts locally. I feel this issue can be closed now, as it concerns an older codebase. If I get any further errors, I shall raise a new issue. @ehildenb  and @dwightguth Thank you for your help!
