### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type MatchError

### ISSUE THREAD

**Issue by prpr2770** [runtimeverification/k#996]
`
$ kompile ./dool.k --debug
scala.MatchError: Some(DOOL.Dool) (of class scala.Some)
	at org.kframework.backend.llvm.matching.pattern.SortCategory$.apply(SortCategory.scala:25)
	at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:92)
	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$10(Generator.scala:99)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Generator$.genPatterns(Generator.scala:99)
	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genClauseMatrix$11(Generator.scala:134)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.backend.llvm.matching.Generator$.genClauseMatrix(Generator.scala:134)
	at org.kframework.backend.llvm.matching.Generator$.mkDecisionTree(Generator.scala:140)
	at org.kframework.backend.llvm.matching.Matching$.$anonfun$writeDecisionTreeToFile$4(Matching.scala:38)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:31)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type MatchError (Some(DOOL.Dool)
(of class scala.Some))
`

**Comment by prpr2770** [comment]
I am trying to define a new Sort and I'm experimenting with it, by modifying Bool definition, to create a new Sort called Dool. The code can be found [here](https://gist.github.com/prpr2770/80fa7bc3ab7087036e6b3fee5f8979f5). When I tried to kompile it, I found the above error.

**Comment by prpr2770** [comment]
If I Kompile it with the Java Backend there's no error.

**Comment by ehildenb** [comment]
A few errors I can see off the bat:

1.   https://gist.github.com/prpr2770/80fa7bc3ab7087036e6b3fee5f8979f5#file-dool-k-L5 There is no hook named `DOOL.Dool`, so you shouldn't have this attribute, or the backend will complain about a missing hook.
2.   https://gist.github.com/prpr2770/80fa7bc3ab7087036e6b3fee5f8979f5#file-dool-k-L28 You are not allowed to extend the builtin sorts (in this case `Bool`) with new data.


You're probably best off avoiding importing the `Bool` sort altogether, if what you want to play with is a boolean algebra that you create yourself.

**Comment by prpr2770** [comment]
Is there any reference documentation that you can share, that helps understand the concept of Hooks and also, on the ways in which we can define a new Sort? 
Thank you for your help with this.

**Comment by prpr2770** [comment]
@ehildenb @dwightguth Thank you for your help with addressing the issues.  I find it difficult to understand different aspects of K-framework, by just reading the codebase. Is there any documentation that you have, which you could share to help me understand about Hooks, and the ways in which properties of Commutativity and Equality between terms can be incorporated into the specification, without relying on Domain.BOOL? 
Thank you for your helpd.

**Comment by ehildenb** [comment]
I think it's unlikely you can remove dependence on `Bool` entirely, because it's used in side-conditions on rules.

Please re-open with a self-contained example if this is still an issue for you.
