### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (None.get)

### ISSUE THREAD

**Issue by prpr2770** [runtimeverification/k#997]
While compiling the same codebase, I get an error when using the default backend, but NO ERROR when using the Java backend. 

Implementing kompilation with the Default Backend produces an error: 
`
$ kompile kat.k --debug
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at org.kframework.backend.llvm.matching.Fringe.expand(Matrix.scala:248)
	at org.kframework.backend.llvm.matching.AHeuristic$.$anonfun$computeScoreForKey$4(Heuristics.scala:151)
	at org.kframework.backend.llvm.matching.AHeuristic$.$anonfun$computeScoreForKey$4$adapted(Heuristics.scala:150)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.kframework.backend.llvm.matching.AHeuristic$.computeScoreForKey(Heuristics.scala:150)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey(Matrix.scala:33)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey$(Matrix.scala:17)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:45)
	at org.kframework.backend.llvm.matching.Column.zeroOrHeuristic$2(Matrix.scala:79)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1$adapted(Matrix.scala:82)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.computeScore(Matrix.scala:71)
	at org.kframework.backend.llvm.matching.Column.score$lzycompute(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:67)
	at org.kframework.backend.llvm.matching.MatrixColumn.score$lzycompute(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.MatrixColumn.score(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.Heuristic$.getBest(Heuristics.scala:27)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx$lzycompute(Matrix.scala:447)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx(Matrix.scala:442)
	at org.kframework.backend.llvm.matching.Matrix.compileInternal(Matrix.scala:622)
	at org.kframework.backend.llvm.matching.Matrix.compile(Matrix.scala:603)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:26)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException
(None.get)
`
Implementing kompilation with the Java Backend doesn't produce any error messages. 
`
$ kompile kat.k --backend java
$ 

`

**Comment by ehildenb** [comment]
The Java backend compilation process checks many fewer things than the LLVM backend (default) does when doing compilation. So this isn't ideal, but it's not surprising.

We probably will not fix this, since we're more focused on deprecating the Java backend in favor of the Haskell backend. Suffice to say, if the LLVM backend complains about something in your definition, you should treat it as an error in your definition, even if the Java backend does not complain.

**Comment by ehildenb** [comment]
Closing this, feel free to re-open if you think it's not resolved.
