### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type NoSuchElementException (None.get)

### ISSUE THREAD

**Issue by prpr2770** [runtimeverification/k#999]
`
user@d63a9f0d4e0a:~/k_project/kat/kat1$ kompile kat.k --debug
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at org.kframework.backend.llvm.matching.Fringe.expand(Matrix.scala:248)
	at org.kframework.backend.llvm.matching.AHeuristic$.$anonfun$computeScoreForKey$4(Heuristics.scala:151)
	at org.kframework.backend.llvm.matching.AHeuristic$.$anonfun$computeScoreForKey$4$adapted(Heuristics.scala:150)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.kframework.backend.llvm.matching.AHeuristic$.computeScoreForKey(Heuristics.scala:150)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey(Matrix.scala:33)
	at org.kframework.backend.llvm.matching.AbstractColumn.computeScoreForKey$(Matrix.scala:17)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:45)
	at org.kframework.backend.llvm.matching.Column.zeroOrHeuristic$2(Matrix.scala:79)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.$anonfun$computeScoreForKey$1$adapted(Matrix.scala:82)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.kframework.backend.llvm.matching.Column.computeScoreForKey(Matrix.scala:82)
	at org.kframework.backend.llvm.matching.Column.computeScore(Matrix.scala:71)
	at org.kframework.backend.llvm.matching.Column.score$lzycompute(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:57)
	at org.kframework.backend.llvm.matching.Column.score(Matrix.scala:67)
	at org.kframework.backend.llvm.matching.MatrixColumn.score$lzycompute(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.MatrixColumn.score(Matrix.scala:42)
	at org.kframework.backend.llvm.matching.Heuristic$.getBest(Heuristics.scala:27)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx$lzycompute(Matrix.scala:447)
	at org.kframework.backend.llvm.matching.Matrix.bestColIx(Matrix.scala:442)
	at org.kframework.backend.llvm.matching.Matrix.compileInternal(Matrix.scala:622)
	at org.kframework.backend.llvm.matching.Matrix.compile(Matrix.scala:603)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:26)
	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
`

**Comment by prpr2770** [comment]
The above error was obtained when using the default LLVM backend for Kompile. The codebase can be found [here](https://gist.github.com/prpr2770/7353a82d86aeb28abd898b2efe1a929c).

**Comment by dwightguth** [comment]
I cannot reproduce this error with the code at the link you provided and the latest version of K. Can I see `kompile --version`?

**Comment by prpr2770** [comment]
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 1cb24c0
Git branch: UNKNOWN
Build date: Fri Dec 20 18:24:40 GMT 2019
